use crate::api;
use axum::routing::{delete, get, post, put};
use axum::{middleware, Router};

pub fn admin_routes() -> Router {
    Router::new()
        // Admin user management routes
        .route(
            "/api/admin/users",
            get(api::user::list_users)
                .layer(middleware::from_fn(api::middleware::users_read_middleware)),
        )
        .route(
            "/api/admin/users/{user_id}",
            get(api::user::get_user)
                .layer(middleware::from_fn(api::middleware::users_read_middleware)),
        )
        .route(
            "/api/admin/users/{user_id}",
            put(api::user::update_user)
                .layer(middleware::from_fn(api::middleware::users_edit_middleware)),
        )
        .route(
            "/api/admin/users/{user_id}/toggle-active",
            post(api::user::toggle_user_active)
                .layer(middleware::from_fn(api::middleware::users_edit_middleware)),
        )
        .route(
            "/api/admin/users/reset-password",
            post(api::user::reset_user_password)
                .layer(middleware::from_fn(api::middleware::users_edit_middleware)),
        )
        .route(
            "/api/admin/users",
            post(api::user::create_user).layer(middleware::from_fn(
                api::middleware::users_create_middleware,
            )),
        )
        .route(
            "/api/admin/users/{user_id}",
            delete(api::user::delete_user).layer(middleware::from_fn(
                api::middleware::users_delete_middleware,
            )),
        )
        // Admin user group management routes
        .route(
            "/api/admin/groups",
            get(api::user_groups::list_user_groups)
                .layer(middleware::from_fn(api::middleware::groups_read_middleware)),
        )
        .route(
            "/api/admin/groups",
            post(api::user_groups::create_user_group).layer(middleware::from_fn(
                api::middleware::groups_create_middleware,
            )),
        )
        .route(
            "/api/admin/groups/{group_id}",
            get(api::user_groups::get_user_group)
                .layer(middleware::from_fn(api::middleware::groups_read_middleware)),
        )
        .route(
            "/api/admin/groups/{group_id}",
            put(api::user_groups::update_user_group)
                .layer(middleware::from_fn(api::middleware::groups_edit_middleware)),
        )
        .route(
            "/api/admin/groups/{group_id}",
            delete(api::user_groups::delete_user_group).layer(middleware::from_fn(
                api::middleware::groups_delete_middleware,
            )),
        )
        .route(
            "/api/admin/groups/{group_id}/members",
            get(api::user_groups::get_group_members)
                .layer(middleware::from_fn(api::middleware::groups_read_middleware)),
        )
        .route(
            "/api/admin/groups/assign",
            post(api::user_groups::assign_user_to_group)
                .layer(middleware::from_fn(api::middleware::groups_edit_middleware)),
        )
        .route(
            "/api/admin/groups/{user_id}/{group_id}/remove",
            delete(api::user_groups::remove_user_from_group)
                .layer(middleware::from_fn(api::middleware::groups_edit_middleware)),
        )
        // User Group Model Provider relationship routes
        .route(
            "/api/admin/groups/{group_id}/model-providers",
            get(api::user_groups::get_group_model_providers)
                .layer(middleware::from_fn(api::middleware::groups_read_middleware)),
        )
        .route(
            "/api/admin/groups/assign-model-provider",
            post(api::user_groups::assign_model_provider_to_group)
                .layer(middleware::from_fn(api::middleware::groups_edit_middleware)),
        )
        .route(
            "/api/admin/groups/{group_id}/model-providers/{provider_id}",
            delete(api::user_groups::remove_model_provider_from_group)
                .layer(middleware::from_fn(api::middleware::groups_edit_middleware)),
        )
        .route(
            "/api/admin/user-group-model-provider-relationships",
            get(api::user_groups::list_user_group_model_provider_relationships)
                .layer(middleware::from_fn(api::middleware::groups_read_middleware)),
        )
        // Admin configuration routes
        .route(
            "/api/admin/config/user-registration",
            get(api::configuration::get_user_registration_status_admin).layer(middleware::from_fn(
                api::middleware::config_user_registration_read_middleware,
            )),
        )
        .route(
            "/api/admin/config/user-registration",
            put(api::configuration::update_user_registration_status).layer(middleware::from_fn(
                api::middleware::config_user_registration_edit_middleware,
            )),
        )
        .route(
            "/api/admin/config/default-language",
            get(api::configuration::get_default_language_admin).layer(middleware::from_fn(
                api::middleware::config_appearance_read_middleware,
            )),
        )
        .route(
            "/api/admin/config/default-language",
            put(api::configuration::update_default_language).layer(middleware::from_fn(
                api::middleware::config_appearance_edit_middleware,
            )),
        )
        .route(
            "/api/admin/config/proxy",
            get(api::configuration::get_proxy_settings).layer(middleware::from_fn(
                api::middleware::config_proxy_read_middleware,
            )),
        )
        .route(
            "/api/admin/config/proxy",
            put(api::configuration::update_proxy_settings).layer(middleware::from_fn(
                api::middleware::config_proxy_edit_middleware,
            )),
        )
        .route(
            "/api/admin/config/proxy/test",
            post(api::configuration::test_proxy_connection).layer(middleware::from_fn(
                api::middleware::config_proxy_read_middleware,
            )),
        )
        // Model provider routes
        .route(
            "/api/admin/model-providers",
            get(api::model_providers::list_model_providers).layer(middleware::from_fn(
                api::middleware::model_providers_read_middleware,
            )),
        )
        .route(
            "/api/admin/model-providers",
            post(api::model_providers::create_model_provider).layer(middleware::from_fn(
                api::middleware::model_providers_create_middleware,
            )),
        )
        .route(
            "/api/admin/model-providers/{provider_id}",
            get(api::model_providers::get_model_provider).layer(middleware::from_fn(
                api::middleware::model_providers_read_middleware,
            )),
        )
        .route(
            "/api/admin/model-providers/{provider_id}",
            put(api::model_providers::update_model_provider).layer(middleware::from_fn(
                api::middleware::model_providers_edit_middleware,
            )),
        )
        .route(
            "/api/admin/model-providers/{provider_id}",
            delete(api::model_providers::delete_model_provider).layer(middleware::from_fn(
                api::middleware::model_providers_delete_middleware,
            )),
        )
        .route(
            "/api/admin/model-providers/{provider_id}/clone",
            post(api::model_providers::clone_model_provider).layer(middleware::from_fn(
                api::middleware::model_providers_create_middleware,
            )),
        )
        .route(
            "/api/admin/model-providers/{provider_id}/test-proxy",
            post(api::model_providers::test_model_provider_proxy_connection).layer(
                middleware::from_fn(api::middleware::model_providers_read_middleware),
            ),
        )
        .route(
            "/api/admin/model-providers/{provider_id}/groups",
            get(api::model_providers::get_provider_groups).layer(middleware::from_fn(
                api::middleware::model_providers_read_middleware,
            )),
        )
        // Model routes
        .route(
            "/api/admin/model-providers/{provider_id}/models",
            post(api::model_providers::create_model).layer(middleware::from_fn(
                api::middleware::model_providers_edit_middleware,
            )),
        )
        .route(
            "/api/admin/models/{model_id}",
            get(api::model_providers::get_model).layer(middleware::from_fn(
                api::middleware::model_providers_read_middleware,
            )),
        )
        .route(
            "/api/admin/models/{model_id}",
            put(api::model_providers::update_model).layer(middleware::from_fn(
                api::middleware::model_providers_edit_middleware,
            )),
        )
        .route(
            "/api/admin/models/{model_id}",
            delete(api::model_providers::delete_model).layer(middleware::from_fn(
                api::middleware::model_providers_delete_middleware,
            )),
        )
        .route(
            "/api/admin/models/{model_id}/start",
            post(api::model_providers::start_model).layer(middleware::from_fn(
                api::middleware::model_providers_edit_middleware,
            )),
        )
        .route(
            "/api/admin/models/{model_id}/stop",
            post(api::model_providers::stop_model).layer(middleware::from_fn(
                api::middleware::model_providers_edit_middleware,
            )),
        )
        .route(
            "/api/admin/models/{model_id}/enable",
            post(api::model_providers::enable_model).layer(middleware::from_fn(
                api::middleware::model_providers_edit_middleware,
            )),
        )
        .route(
            "/api/admin/models/{model_id}/disable",
            post(api::model_providers::disable_model).layer(middleware::from_fn(
                api::middleware::model_providers_edit_middleware,
            )),
        )
        // Assistant routes - Admin endpoints
        .route(
            "/api/admin/assistants",
            get(api::assistants::list_assistants_admin)
                .layer(middleware::from_fn(api::middleware::groups_read_middleware)),
        )
        .route(
            "/api/admin/assistants",
            post(api::assistants::create_template_assistant).layer(middleware::from_fn(
                api::middleware::groups_create_middleware,
            )),
        )
        .route(
            "/api/admin/assistants/{assistant_id}",
            get(api::assistants::get_assistant_admin)
                .layer(middleware::from_fn(api::middleware::groups_read_middleware)),
        )
        .route(
            "/api/admin/assistants/{assistant_id}",
            put(api::assistants::update_assistant_admin)
                .layer(middleware::from_fn(api::middleware::groups_edit_middleware)),
        )
        .route(
            "/api/admin/assistants/{assistant_id}",
            delete(api::assistants::delete_assistant_admin).layer(middleware::from_fn(
                api::middleware::groups_delete_middleware,
            )),
        )
        // Model upload routes for Candle models
        .route(
            "/api/admin/uploaded-models",
            post(api::model_uploads::create_model).layer(middleware::from_fn(
                api::middleware::model_providers_create_middleware,
            )),
        )
        .route(
            "/api/admin/uploaded-models",
            get(api::model_uploads::list_models).layer(middleware::from_fn(
                api::middleware::model_providers_read_middleware,
            )),
        )
        .route(
            "/api/admin/uploaded-models/{model_id}",
            get(api::model_uploads::get_model).layer(middleware::from_fn(
                api::middleware::model_providers_read_middleware,
            )),
        )
        .route(
            "/api/admin/uploaded-models/{model_id}",
            put(api::model_uploads::update_model).layer(middleware::from_fn(
                api::middleware::model_providers_edit_middleware,
            )),
        )
        .route(
            "/api/admin/uploaded-models/{model_id}",
            delete(api::model_uploads::delete_model).layer(middleware::from_fn(
                api::middleware::model_providers_delete_middleware,
            )),
        )
        .route(
            "/api/admin/uploaded-models/{model_id}/upload",
            post(api::model_uploads::upload_model_file).layer(middleware::from_fn(
                api::middleware::model_providers_edit_middleware,
            )),
        )
        .route(
            "/api/admin/uploaded-models/{model_id}/validate",
            post(api::model_uploads::validate_model).layer(middleware::from_fn(
                api::middleware::model_providers_edit_middleware,
            )),
        )
        .route(
            "/api/admin/uploaded-models/{model_id}/status",
            put(api::model_uploads::update_model_status).layer(middleware::from_fn(
                api::middleware::model_providers_edit_middleware,
            )),
        )
        .route(
            "/api/admin/uploaded-models/storage-stats",
            get(api::model_uploads::get_storage_stats).layer(middleware::from_fn(
                api::middleware::model_providers_read_middleware,
            )),
        )
}