/**
 * Generated API endpoint definitions
 * Auto-generated from OpenAPI specification
 * 
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY ⚠️
 * This file is automatically generated from the OpenAPI specification generated from the server code.
 */

// =============================================================================
// TYPE DEFINITIONS
// =============================================================================

export interface ApiProxyServerConfig {
  port: number
  address: string
  prefix: string
  api_key: string
  allow_cors: boolean
  log_level: string
  autostart_on_startup: boolean
}

export interface ApiProxyServerModel {
  id: string
  model_id: string
  alias_id?: string | null
  enabled: boolean
  is_default: boolean
  created_at: string
  updated_at: string
}

export interface ApiProxyServerStatus {
  running: boolean
  active_models: number
  server_url?: string | null
}

export interface ApiProxyServerTrustedHost {
  description?: string | null
  id: string
  host: string
  enabled: boolean
  created_at: string
  updated_at: string
}

export interface AssignProviderToGroupRequest {
  group_id: string
  provider_id: string
}

export interface AssignUserToGroupRequest {
  user_id: string
  group_id: string
}

export interface Assistant {
  description?: string | null
  id: string
  name: string
  instructions?: string | null
  parameters?: any
  created_by?: string | null
  is_template: boolean
  is_default: boolean
  is_active: boolean
  created_at: string
  updated_at: string
}

export interface AssistantListResponse {
  assistants: Assistant[]
  total: number
  page: number
  per_page: number
}

export interface AuthResponse {
  token: string
  user: User
  expires_at: string
}

export interface AvailableDevicesResponse {
  devices: DeviceInfo[]
  default_device_type: string
  supports_multi_gpu: boolean
}

export interface CPUInfo {
  model: string
  architecture: string
  cores: number
  threads?: number | null
  base_frequency?: number | null
  max_frequency?: number | null
}

export interface ChatMessageRequest {
  conversation_id: string
  content: string
  model_id: string
  assistant_id: string
  file_ids?: any | null
}

export interface Conversation {
  title: string
  id: string
  user_id: string
  project_id?: string | null
  assistant_id?: string | null
  model_id?: string | null
  active_branch_id?: string | null
  created_at: string
  updated_at: string
}

export interface ConversationListResponse {
  conversations: ConversationSummary[]
  total: number
  page: number
  per_page: number
}

export interface ConversationSummary {
  title: string
  id: string
  user_id: string
  project_id?: string | null
  assistant_id?: string | null
  model_id?: string | null
  created_at: string
  updated_at: string
  last_message?: string | null
  message_count: number
}

export interface CreateApiProxyServerModelRequest {
  model_id: string
  alias_id?: string | null
  enabled?: boolean | null
  is_default?: boolean | null
}

export interface CreateAssistantRequest {
  description?: string | null
  name: string
  instructions?: string | null
  parameters?: any
  is_template?: boolean | null
  is_default?: boolean | null
}

export interface CreateConversationRequest {
  title: string
  project_id?: string | null
  assistant_id: string
  model_id: string
}

export interface CreateModelRequest {
  description?: string | null
  provider_id: string
  name: string
  alias: string
  enabled?: boolean | null
  capabilities?: any
  parameters?: any
  engine_type: string
  engine_settings_mistralrs?: any
  engine_settings_llamacpp?: any
  file_format: string
  source?: any
}

export interface CreateProjectRequest {
  description?: string | null
  name: string
  instruction?: string | null
}

export interface CreateProviderRequest {
  type: string
  name: string
  enabled?: boolean | null
  api_key?: string | null
  base_url?: string | null
  proxy_settings?: any
}

export interface CreateRAGDatabaseRequest {
  description?: string | null
  name: string
  alias: string
  enabled?: boolean | null
  collection_name?: string | null
  embedding_model?: string | null
  chunk_size?: number | null
  chunk_overlap?: number | null
  capabilities?: any
  settings?: any
}

export interface CreateRAGProviderRequest {
  type: string
  name: string
  enabled?: boolean | null
  api_key?: string | null
  base_url?: string | null
}

export interface CreateRAGRepositoryRequest {
  description?: string | null
  name: string
  url: string
  enabled?: boolean | null
  requires_auth?: boolean | null
  auth_token?: string | null
  priority?: number | null
}

export interface CreateRepositoryRequest {
  name: string
  url: string
  auth_type: string
  auth_config?: any
  enabled?: boolean | null
}

export interface CreateTrustedHostRequest {
  description?: string | null
  host: string
  enabled?: boolean | null
}

export interface CreateUserGroupRequest {
  description?: string | null
  name: string
  permissions: any
  provider_ids?: any | null
}

export interface CreateUserRequest {
  username: string
  email: string
  password: string
  profile?: any
}

export interface DefaultLanguageResponse {
  language: string
}

export interface DeviceInfo {
  id: number
  name: string
  device_type: string
  memory_total?: number | null
  memory_free?: number | null
  is_available: boolean
}

export interface DownloadFromRepositoryRequest {
  description?: string | null
  provider_id: string
  repository_id: string
  repository_path: string
  repository_branch?: string | null
  name: string
  alias: string
  file_format: string
  main_filename: string
  capabilities?: any
  parameters?: any
  engine_type?: string | null
  engine_settings_mistralrs?: any
  source: SourceInfo
}

export interface DownloadInstance {
  id: string
  provider_id: string
  repository_id: string
  request_data: DownloadRequestData
  status: DownloadStatus
  progress_data?: any
  error_message?: string | null
  started_at: string
  completed_at?: string | null
  model_id?: string | null
  created_at: string
  updated_at: string
}

export interface DownloadPaginationQuery {
  page?: number | null
  per_page?: number | null
  status?: string | null
}

export interface DownloadProgressData {
  phase?: string | null
  current?: number | null
  total?: number | null
  message?: string | null
  speed_bps?: number | null
  eta_seconds?: number | null
}

export interface DownloadRAGDatabaseFromRepositoryRequest {
  repository_id: string
  database_id: string
  target_provider_id: string
  database_name?: string | null
  database_alias?: string | null
}

export interface DownloadRequestData {
  description?: string | null
  model_name: string
  revision?: string | null
  files?: any | null
  quantization?: string | null
  repository_path?: string | null
  alias?: string | null
  file_format?: string | null
  main_filename?: string | null
  capabilities?: any
  parameters?: any
  engine_type?: string | null
  engine_settings_mistralrs?: any
  source?: any
}

export type DownloadStatus = string

export interface DownloadTokenParams {
  token?: string | null
}

export interface DownloadTokenResponse {
  token: string
  expires_at: string
}

export interface EngineInfo {
  description?: string | null
  engine_type: string
  name: string
  version: string
  status: string
  supported_architectures?: any | null
  required_dependencies?: any | null
}

export interface File {
  id: string
  user_id: string
  filename: string
  file_size: number
  mime_type?: string | null
  checksum?: string | null
  project_id?: string | null
  thumbnail_count: number
  page_count: number
  processing_metadata: any
  created_at: string
  updated_at: string
}

export interface FileListParams {
  page?: number | null
  per_page?: number | null
  search?: string | null
}

export interface FileListResponse {
  files: File[]
  total: number
  page: number
  per_page: number
}

export interface FileOperationSuccessResponse {
  success: boolean
}

export interface GPUComputeCapabilities {
  cuda_support: boolean
  cuda_version?: string | null
  metal_support: boolean
  opencl_support: boolean
  vulkan_support?: boolean | null
}

export interface GPUDevice {
  device_id: string
  name: string
  vendor: string
  memory?: number | null
  driver_version?: string | null
  compute_capabilities: GPUComputeCapabilities
}

export interface HardwareInfo {
  operating_system: OperatingSystemInfo
  cpu: CPUInfo
  memory: MemoryInfo
  gpu_devices: GPUDevice[]
}

export interface HardwareInfoResponse {
  hardware: HardwareInfo
}

export interface HubAssistant {
  description?: string | null
  id: string
  name: string
  instructions?: string | null
  parameters?: any
  category: string
  tags: string[]
  recommended_models: string[]
  capabilities_required: string[]
  popularity_score?: number | null
  author?: string | null
  use_cases?: any | null
  example_prompts?: any | null
}

export interface HubData {
  models: HubModel[]
  assistants: HubAssistant[]
  hub_version: string
  last_updated: string
}

export interface HubModel {
  description?: string | null
  id: string
  name: string
  alias: string
  repository_url: string
  repository_path: string
  main_filename: string
  file_format: string
  capabilities?: any
  size_gb: number
  tags: string[]
  recommended_parameters?: any
  public: boolean
  popularity_score?: number | null
  license?: string | null
  quantization_options?: any | null
  context_length?: number | null
  language_support?: any | null
}

export interface HubQueryParams {
  lang?: string | null
}

export interface HubVersionResponse {
  hub_version: string
}

export interface InitResponse {
  needs_setup: boolean
  is_desktop: boolean
  token?: string | null
}

export interface LlamaCppSettings {
  device_type?: string | null
  device_ids?: any | null
  ctx_size?: number | null
  batch_size?: number | null
  ubatch_size?: number | null
  parallel?: number | null
  keep?: number | null
  mlock?: boolean | null
  no_mmap?: boolean | null
  threads?: number | null
  threads_batch?: number | null
  cont_batching?: boolean | null
  flash_attn?: boolean | null
  no_kv_offload?: boolean | null
  n_gpu_layers?: number | null
  main_gpu?: number | null
  split_mode?: string | null
  tensor_split?: string | null
  rope_freq_base?: number | null
  rope_freq_scale?: number | null
  rope_scaling?: string | null
  cache_type_k?: string | null
  cache_type_v?: string | null
  seed?: number | null
  numa?: string | null
}

export interface LoginRequest {
  username_or_email: string
  password: string
}

export interface MemoryInfo {
  total_ram: number
  total_swap?: number | null
}

export interface MistralRsSettings {
  command?: string | null
  model_id_name?: string | null
  tokenizer_json?: string | null
  arch?: string | null
  quantized_filename?: string | null
  weight_file?: string | null
  device_type?: string | null
  device_ids?: any | null
  num_device_layers?: any | null
  cpu?: boolean | null
  max_seqs?: number | null
  max_seq_len?: number | null
  no_kv_cache?: boolean | null
  truncate_sequence?: boolean | null
  paged_attn_gpu_mem?: number | null
  paged_attn_gpu_mem_usage?: number | null
  paged_ctxt_len?: number | null
  paged_attn_block_size?: number | null
  no_paged_attn?: boolean | null
  paged_attn?: boolean | null
  chat_template?: string | null
  jinja_explicit?: string | null
  prefix_cache_n?: number | null
  prompt_chunksize?: number | null
  dtype?: string | null
  in_situ_quant?: string | null
  seed?: number | null
  max_edge?: number | null
  max_num_images?: number | null
  max_image_length?: number | null
  serve_ip?: string | null
  log_file?: string | null
  enable_search?: boolean | null
  search_bert_model?: string | null
  interactive_mode?: boolean | null
  enable_thinking?: boolean | null
  token_source?: string | null
}

export interface Model {
  description?: string | null
  id: string
  provider_id: string
  name: string
  alias: string
  enabled: boolean
  is_deprecated: boolean
  is_active: boolean
  capabilities?: any
  parameters?: any
  created_at: string
  updated_at: string
  file_size_bytes?: number | null
  validation_status?: string | null
  validation_issues?: any | null
  port?: number | null
  pid?: number | null
  engine_type: string
  engine_settings_mistralrs?: any
  engine_settings_llamacpp?: any
  file_format: string
  source?: any
  files?: any | null
}

export interface ModelCapabilities {
  vision?: boolean | null
  audio?: boolean | null
  tools?: boolean | null
  code_interpreter?: boolean | null
}

export interface ModelFileInfo {
  filename: string
  file_size_bytes: number
  file_type: string
  uploaded_at: string
}

export interface ModelParameters {
  max_tokens?: number | null
  temperature?: number | null
  top_k?: number | null
  top_p?: number | null
  min_p?: number | null
  repeat_last_n?: number | null
  repeat_penalty?: number | null
  presence_penalty?: number | null
  frequency_penalty?: number | null
  seed?: number | null
  stop?: any | null
}

export interface NgrokSettingsResponse {
  api_key: string
  tunnel_enabled: boolean
  tunnel_url?: string | null
  tunnel_status: string
  auto_start: boolean
  domain?: string | null
}

export interface NgrokStatusResponse {
  tunnel_active: boolean
  tunnel_url?: string | null
  tunnel_status: string
  last_error?: string | null
}

export interface OperatingSystemInfo {
  name: string
  version: string
  kernel_version?: string | null
  architecture: string
}

export interface OperationSuccessResponse {
  success: boolean
  message: string
}

export interface PaginationQuery {
  page?: number | null
  per_page?: number | null
}

export interface PaginationQuery2 {
  page?: number | null
  per_page?: number | null
}

export interface PaginationQuery3 {
  page?: number | null
  per_page?: number | null
}

export interface PaginationQuery4 {
  page?: number | null
  per_page?: number | null
}

export interface PaginationQuery5 {
  page?: number | null
  per_page?: number | null
}

export interface PaginationQuery6 {
  page?: number | null
  per_page?: number | null
}

export interface PaginationQuery7 {
  page?: number | null
  per_page?: number | null
}

export interface PaginationQuery8 {
  page?: number | null
  per_page?: number | null
  project_id?: string | null
}

export interface PasswordService {
  bcrypt: string
  salt: string
}

export interface PreviewParams {
  page?: number | null
}

export interface Project {
  description?: string | null
  id: string
  user_id: string
  name: string
  instruction?: string | null
  created_at: string
  updated_at: string
}

export interface ProjectDetailResponse {
  project: Project
  conversations: Conversation[]
}

export interface ProjectListQuery {
  page?: number | null
  per_page?: number | null
  search?: string | null
}

export interface ProjectListResponse {
  projects: Project[]
  total: number
  page: number
  per_page: number
}

export interface Provider {
  type: string
  id: string
  name: string
  enabled: boolean
  api_key?: string | null
  base_url?: string | null
  built_in: boolean
  proxy_settings?: any
  created_at: string
  updated_at: string
}

export interface ProviderListResponse {
  providers: Provider[]
  total: number
  page: number
  per_page: number
}

export interface ProxySettings {
  enabled?: boolean
  url?: string
  username?: string
  password?: string
  no_proxy?: string
  ignore_ssl_certificates?: boolean
}

export interface ProxySettingsResponse {
  enabled: boolean
  url: string
  username: string
  password: string
  no_proxy: string
  ignore_ssl_certificates: boolean
}

export interface RAGDatabase {
  description?: string | null
  id: string
  provider_id: string
  name: string
  alias: string
  enabled: boolean
  is_active: boolean
  collection_name?: string | null
  embedding_model?: string | null
  chunk_size: number
  chunk_overlap: number
  capabilities?: any
  settings?: any
  created_at: string
  updated_at: string
}

export interface RAGDatabaseCapabilities {
  semantic_search?: boolean | null
  hybrid_search?: boolean | null
  metadata_filtering?: boolean | null
  similarity_threshold?: boolean | null
}

export interface RAGProvider {
  type: string
  id: string
  name: string
  enabled: boolean
  api_key?: string | null
  base_url?: string | null
  built_in: boolean
  proxy_settings?: any
  created_at: string
  updated_at: string
}

export interface RAGProviderListResponse {
  providers: RAGProvider[]
  total: number
  page: number
  per_page: number
}

export interface RAGRepository {
  description?: string | null
  id: string
  name: string
  url: string
  enabled: boolean
  requires_auth: boolean
  auth_token?: string | null
  priority: number
  created_at: string
  updated_at: string
}

export interface RAGRepositoryConnectionTestResponse {
  success: boolean
  message: string
  available_databases_count?: number | null
}

export interface RAGRepositoryListResponse {
  repositories: RAGRepository[]
  total: number
  page: number
  per_page: number
}

export interface Repository {
  id: string
  name: string
  url: string
  auth_type: string
  auth_config?: any
  enabled: boolean
  built_in: boolean
  created_at: string
  updated_at: string
}

export interface RepositoryAuthConfig {
  api_key?: string | null
  username?: string | null
  password?: string | null
  token?: string | null
  auth_test_api_endpoint?: string | null
}

export interface RepositoryListResponse {
  repositories: Repository[]
  total: number
  page: number
  per_page: number
}

export interface ResetPasswordRequest {
  user_id: string
  new_password: string
}

export interface SearchQuery {
  q: string
  page?: number | null
  per_page?: number | null
  project_id?: string | null
}

export interface SourceInfo {
  type: string
  id?: string | null
}

export interface SwitchBranchRequest {
  branch_id: string
}

export interface TestProxyConnectionRequest {
  enabled: boolean
  url: string
  username: string
  password: string
  no_proxy: string
  ignore_ssl_certificates: boolean
}

export interface TestProxyConnectionResponse {
  success: boolean
  message: string
}

export interface TestRepositoryConnectionRequest {
  name: string
  url: string
  auth_type: string
  auth_config?: any
}

export interface TestRepositoryConnectionResponse {
  success: boolean
  message: string
}

export interface UpdateApiProxyServerModelRequest {
  alias_id?: string | null
  enabled?: boolean | null
  is_default?: boolean | null
}

export interface UpdateAssistantRequest {
  description?: string | null
  name?: string | null
  instructions?: string | null
  parameters?: any
  is_template?: boolean | null
  is_default?: boolean | null
  is_active?: boolean | null
}

export interface UpdateConversationRequest {
  title?: string | null
  assistant_id?: string | null
  model_id?: string | null
}

export interface UpdateDefaultLanguageRequest {
  language: string
}

export interface UpdateModelRequest {
  description?: string | null
  name?: string | null
  alias?: string | null
  enabled?: boolean | null
  is_active?: boolean | null
  capabilities?: any
  parameters?: any
  engine_type?: string | null
  engine_settings_mistralrs?: any
  engine_settings_llamacpp?: any
  file_format?: string | null
}

export interface UpdateNgrokSettingsRequest {
  api_key?: string | null
  tunnel_enabled?: boolean | null
  auto_start?: boolean | null
  domain?: string | null
}

export interface UpdateProjectRequest {
  description?: string | null
  name?: string | null
  instruction?: string | null
}

export interface UpdateProviderRequest {
  name?: string | null
  enabled?: boolean | null
  api_key?: string | null
  base_url?: string | null
  proxy_settings?: any
}

export interface UpdateProxySettingsRequest {
  enabled: boolean
  url: string
  username: string
  password: string
  no_proxy: string
  ignore_ssl_certificates: boolean
}

export interface UpdateRAGDatabaseRequest {
  description?: string | null
  name?: string | null
  alias?: string | null
  enabled?: boolean | null
  collection_name?: string | null
  embedding_model?: string | null
  chunk_size?: number | null
  chunk_overlap?: number | null
  capabilities?: any
  settings?: any
}

export interface UpdateRAGProviderRequest {
  name?: string | null
  enabled?: boolean | null
  api_key?: string | null
  base_url?: string | null
  proxy_settings?: any
}

export interface UpdateRAGRepositoryRequest {
  description?: string | null
  name?: string | null
  url?: string | null
  enabled?: boolean | null
  requires_auth?: boolean | null
  auth_token?: string | null
  priority?: number | null
}

export interface UpdateRepositoryRequest {
  name?: string | null
  url?: string | null
  auth_type?: string | null
  auth_config?: any
  enabled?: boolean | null
}

export interface UpdateTrustedHostRequest {
  description?: string | null
  host?: string | null
  enabled?: boolean | null
}

export interface UpdateUserGroupRequest {
  description?: string | null
  name?: string | null
  permissions?: any
  provider_ids?: any | null
  is_active?: boolean | null
}

export interface UpdateUserPasswordRequest {
  current_password?: string | null
  new_password: string
}

export interface UpdateUserRegistrationRequest {
  enabled: boolean
}

export interface UpdateUserRequest {
  username?: string | null
  email?: string | null
  is_active?: boolean | null
  profile?: any
}

export interface UploadFileResponse {
  file: File
}

export interface User {
  id: string
  username: string
  emails: UserEmail[]
  created_at: string
  profile?: any
  services: UserServices
  is_active: boolean
  is_protected: boolean
  last_login_at?: string | null
  updated_at: string
  groups: UserGroup[]
}

export interface UserActiveStatusResponse {
  is_active: boolean
}

export interface UserEmail {
  id: string
  user_id: string
  address: string
  verified: boolean
  created_at: string
}

export interface UserGroup {
  description?: string | null
  id: string
  name: string
  permissions: any
  provider_ids: string[]
  is_protected: boolean
  is_active: boolean
  created_at: string
  updated_at: string
}

export interface UserGroupListResponse {
  groups: UserGroup[]
  total: number
  page: number
  per_page: number
}

export interface UserGroupProviderResponse {
  id: string
  group_id: string
  provider_id: string
  assigned_at: string
  provider: Provider
  group: UserGroup
}

export interface UserHello {
  name: string
}

export interface UserListResponse {
  users: User[]
  total: number
  page: number
  per_page: number
}

export interface UserRegistrationStatusResponse {
  enabled: boolean
}

export interface UserServices {
  password?: any
}

export interface UserSetting {
  id: string
  user_id: string
  key: string
  value: any
  created_at: string
  updated_at: string
}

export interface UserSettingRequest {
  key: string
  value: any
}

export interface UserSettingsDeletionResponse {
  deleted: number
}

export interface UserSettingsResponse {
  settings: UserSetting[]
}

// =============================================================================
// API ENDPOINTS
// =============================================================================

// API endpoint definitions
export const ApiEndpoints = {
  'Admin.addApiProxyServerTrustedHost': 'POST /api/admin/api-proxy-server/trusted-hosts',
  'Admin.addDatabaseToRAGProvider': 'POST /api/admin/rag-providers/{provider_id}/databases',
  'Admin.addModelToApiProxyServer': 'POST /api/admin/api-proxy-server/models',
  'Admin.addModelToProvider': 'POST /api/admin/providers/{provider_id}/models',
  'Admin.assignProviderToGroup': 'POST /api/admin/groups/assign-provider',
  'Admin.assignUserToGroup': 'POST /api/admin/groups/assign',
  'Admin.cancelDownload': 'POST /api/admin/downloads/{download_id}/cancel',
  'Admin.cloneRAGProvider': 'POST /api/admin/rag-providers/{provider_id}/clone',
  'Admin.createAssistant': 'POST /api/admin/assistants',
  'Admin.createGroup': 'POST /api/admin/groups',
  'Admin.createProvider': 'POST /api/admin/providers',
  'Admin.createRAGProvider': 'POST /api/admin/rag-providers',
  'Admin.createRAGRepository': 'POST /api/admin/rag-repositories',
  'Admin.createRepository': 'POST /api/admin/repositories',
  'Admin.createUser': 'POST /api/admin/users',
  'Admin.deleteAssistant': 'DELETE /api/admin/assistants/{assistant_id}',
  'Admin.deleteDownload': 'DELETE /api/admin/downloads/{download_id}',
  'Admin.deleteGroup': 'DELETE /api/admin/groups/{group_id}',
  'Admin.deleteModel': 'DELETE /api/admin/models/{model_id}',
  'Admin.deleteProvider': 'DELETE /api/admin/providers/{provider_id}',
  'Admin.deleteRAGDatabase': 'DELETE /api/admin/rag-databases/{database_id}',
  'Admin.deleteRAGProvider': 'DELETE /api/admin/rag-providers/{provider_id}',
  'Admin.deleteRAGRepository': 'DELETE /api/admin/rag-repositories/{repository_id}',
  'Admin.deleteRepository': 'DELETE /api/admin/repositories/{repository_id}',
  'Admin.deleteUser': 'DELETE /api/admin/users/{user_id}',
  'Admin.disableModel': 'POST /api/admin/models/{model_id}/disable',
  'Admin.disableRAGDatabase': 'POST /api/admin/rag-databases/{database_id}/disable',
  'Admin.downloadFromRepository': 'POST /api/admin/models/initiate-repository-download',
  'Admin.downloadRAGDatabaseFromRepository': 'POST /api/admin/rag-repositories/download-database',
  'Admin.enableModel': 'POST /api/admin/models/{model_id}/enable',
  'Admin.enableRAGDatabase': 'POST /api/admin/rag-databases/{database_id}/enable',
  'Admin.getApiProxyServerConfig': 'GET /api/admin/api-proxy-server/config',
  'Admin.getApiProxyServerStatus': 'GET /api/admin/api-proxy-server/status',
  'Admin.getAssistant': 'GET /api/admin/assistants/{assistant_id}',
  'Admin.getAvailableDevices': 'GET /api/admin/devices',
  'Admin.getDefaultLanguage': 'GET /api/admin/config/default-language',
  'Admin.getDownload': 'GET /api/admin/downloads/{download_id}',
  'Admin.getGroup': 'GET /api/admin/groups/{group_id}',
  'Admin.getGroupMembers': 'GET /api/admin/groups/{group_id}/members',
  'Admin.getGroupProviders': 'GET /api/admin/groups/{group_id}/providers',
  'Admin.getHardwareInfo': 'GET /api/admin/hardware',
  'Admin.getModel': 'GET /api/admin/models/{model_id}',
  'Admin.getNgrokSettings': 'GET /api/admin/config/ngrok',
  'Admin.getNgrokStatus': 'GET /api/admin/config/ngrok/status',
  'Admin.getProvider': 'GET /api/admin/providers/{provider_id}',
  'Admin.getProviderGroups': 'GET /api/admin/providers/{provider_id}/groups',
  'Admin.getProxySettings': 'GET /api/admin/config/proxy',
  'Admin.getRAGDatabase': 'GET /api/admin/rag-databases/{database_id}',
  'Admin.getRAGProvider': 'GET /api/admin/rag-providers/{provider_id}',
  'Admin.getRAGRepository': 'GET /api/admin/rag-repositories/{repository_id}',
  'Admin.getRepository': 'GET /api/admin/repositories/{repository_id}',
  'Admin.getUser': 'GET /api/admin/users/{user_id}',
  'Admin.getUserRegistrationStatus': 'GET /api/admin/config/user-registration',
  'Admin.listAllDownloads': 'GET /api/admin/downloads',
  'Admin.listApiProxyServerModels': 'GET /api/admin/api-proxy-server/models',
  'Admin.listApiProxyServerTrustedHosts': 'GET /api/admin/api-proxy-server/trusted-hosts',
  'Admin.listAssistants': 'GET /api/admin/assistants',
  'Admin.listEngines': 'GET /api/admin/engines',
  'Admin.listGroups': 'GET /api/admin/groups',
  'Admin.listProviderModels': 'GET /api/admin/providers/{provider_id}/models',
  'Admin.listProviders': 'GET /api/admin/providers',
  'Admin.listRAGProviderDatabases': 'GET /api/admin/rag-providers/{provider_id}/databases',
  'Admin.listRAGProviders': 'GET /api/admin/rag-providers',
  'Admin.listRAGRepositories': 'GET /api/admin/rag-repositories',
  'Admin.listRAGRepositoryDatabases': 'GET /api/admin/rag-repositories/{repository_id}/databases',
  'Admin.listRepositories': 'GET /api/admin/repositories',
  'Admin.listUserGroupProviderRelationships': 'GET /api/admin/user-group-provider-relationships',
  'Admin.listUsers': 'GET /api/admin/users',
  'Admin.reloadApiProxyServerModels': 'POST /api/admin/api-proxy-server/reload/models',
  'Admin.reloadApiProxyServerTrustedHosts': 'POST /api/admin/api-proxy-server/reload/trusted-hosts',
  'Admin.removeApiProxyServerTrustedHost': 'DELETE /api/admin/api-proxy-server/trusted-hosts/{host_id}',
  'Admin.removeModelFromApiProxyServer': 'DELETE /api/admin/api-proxy-server/models/{model_id}',
  'Admin.removeProviderFromGroup': 'DELETE /api/admin/groups/{group_id}/providers/{provider_id}',
  'Admin.removeUserFromGroup': 'DELETE /api/admin/groups/{user_id}/{group_id}/remove',
  'Admin.resetUserPassword': 'POST /api/admin/users/reset-password',
  'Admin.startApiProxyServer': 'POST /api/admin/api-proxy-server/start',
  'Admin.startModel': 'POST /api/admin/models/{model_id}/start',
  'Admin.startNgrokTunnel': 'POST /api/admin/config/ngrok/start',
  'Admin.startRAGDatabase': 'POST /api/admin/rag-databases/{database_id}/start',
  'Admin.stopApiProxyServer': 'POST /api/admin/api-proxy-server/stop',
  'Admin.stopModel': 'POST /api/admin/models/{model_id}/stop',
  'Admin.stopNgrokTunnel': 'POST /api/admin/config/ngrok/stop',
  'Admin.stopRAGDatabase': 'POST /api/admin/rag-databases/{database_id}/stop',
  'Admin.subscribeApiProxyServerLogs': 'GET /api/admin/api-proxy-server/logs/stream',
  'Admin.subscribeDownloadProgress': 'GET /api/admin/downloads/subscribe',
  'Admin.subscribeHardwareUsage': 'GET /api/admin/hardware/usage-stream',
  'Admin.testRAGRepositoryConnection': 'POST /api/admin/rag-repositories/{repository_id}/test-connection',
  'Admin.testRepositoryConnection': 'POST /api/admin/repositories/test',
  'Admin.toggleUserActive': 'POST /api/admin/users/{user_id}/toggle-active',
  'Admin.updateApiProxyServerConfig': 'PUT /api/admin/api-proxy-server/config',
  'Admin.updateApiProxyServerModel': 'PUT /api/admin/api-proxy-server/models/{model_id}',
  'Admin.updateApiProxyServerTrustedHost': 'PUT /api/admin/api-proxy-server/trusted-hosts/{host_id}',
  'Admin.updateAssistant': 'PUT /api/admin/assistants/{assistant_id}',
  'Admin.updateDefaultLanguage': 'PUT /api/admin/config/default-language',
  'Admin.updateGroup': 'PUT /api/admin/groups/{group_id}',
  'Admin.updateModel': 'PUT /api/admin/models/{model_id}',
  'Admin.updateNgrokSettings': 'PUT /api/admin/config/ngrok',
  'Admin.updateProvider': 'PUT /api/admin/providers/{provider_id}',
  'Admin.updateProxySettings': 'PUT /api/admin/config/proxy',
  'Admin.updateRAGDatabase': 'PUT /api/admin/rag-databases/{database_id}',
  'Admin.updateRAGProvider': 'PUT /api/admin/rag-providers/{provider_id}',
  'Admin.updateRAGRepository': 'PUT /api/admin/rag-repositories/{repository_id}',
  'Admin.updateRepository': 'PUT /api/admin/repositories/{repository_id}',
  'Admin.updateUser': 'PUT /api/admin/users/{user_id}',
  'Admin.updateUserRegistrationStatus': 'PUT /api/admin/config/user-registration',
  'Admin.uploadAndCommitModel': 'POST /api/admin/uploaded-models/upload-and-commit',
  'Assistants.createAssistant': 'POST /api/assistants',
  'Assistants.deleteAssistant': 'DELETE /api/assistants/{assistant_id}',
  'Assistants.getAssistant': 'GET /api/assistants/{assistant_id}',
  'Assistants.getDefaultAssistant': 'GET /api/assistants/default',
  'Assistants.listAssistants': 'GET /api/assistants',
  'Assistants.updateAssistant': 'PUT /api/assistants/{assistant_id}',
  'Auth.init': 'GET /api/auth/init',
  'Auth.login': 'POST /api/auth/login',
  'Auth.logout': 'POST /api/auth/logout',
  'Auth.me': 'GET /api/auth/me',
  'Auth.register': 'POST /api/auth/register',
  'Auth.setup': 'POST /api/auth/setup',
  'Chat.createConversation': 'POST /api/chat/conversations',
  'Chat.deleteConversation': 'DELETE /api/chat/conversations/{conversation_id}',
  'Chat.editMessageStream': 'PUT /api/chat/messages/{message_id}/stream',
  'Chat.getConversation': 'GET /api/chat/conversations/{conversation_id}',
  'Chat.getConversationMessagesByBranch': 'GET /api/chat/conversations/{conversation_id}/messages/{branch_id}',
  'Chat.getMessageBranches': 'GET /api/chat/messages/{message_id}/branches',
  'Chat.listConversations': 'GET /api/chat/conversations',
  'Chat.searchConversations': 'GET /api/chat/conversations/search',
  'Chat.sendMessageStream': 'POST /api/chat/messages/stream',
  'Chat.switchConversationBranch': 'PUT /api/chat/conversations/{conversation_id}/branch/switch',
  'Chat.updateConversation': 'PUT /api/chat/conversations/{conversation_id}',
  'Config.getDefaultLanguage': 'GET /api/config/default-language',
  'Config.getUserRegistrationStatus': 'GET /api/config/user-registration',
  'Files.deleteFile': 'DELETE /api/files/{id}',
  'Files.downloadFile': 'GET /api/files/{id}/download',
  'Files.downloadFileWithToken': 'GET /api/files/{id}/download-with-token',
  'Files.generateDownloadToken': 'POST /api/files/{id}/download-token',
  'Files.getFile': 'GET /api/files/{id}',
  'Files.getFilePreview': 'GET /api/files/{id}/preview',
  'Files.listMessageFiles': 'GET /api/messages/{id}/files',
  'Files.listProjectFiles': 'GET /api/projects/{id}/files',
  'Files.removeFileFromMessage': 'DELETE /api/files/{file_id}/messages/{message_id}',
  'Files.uploadFile': 'POST /api/files/upload',
  'Files.uploadProjectFile': 'POST /api/projects/{id}/files',
  'Hub.getHubData': 'GET /api/hub/data',
  'Hub.getHubVersion': 'GET /api/hub/version',
  'Hub.refreshHubData': 'POST /api/hub/refresh',
  'Models.listEnabledProviderModels': 'GET /api/providers/{provider_id}/models',
  'Projects.createProject': 'POST /api/projects',
  'Projects.deleteProject': 'DELETE /api/projects/{project_id}',
  'Projects.getProject': 'GET /api/projects/{project_id}',
  'Projects.linkConversation': 'POST /api/projects/{project_id}/conversations/{conversation_id}',
  'Projects.listProjects': 'GET /api/projects',
  'Projects.unlinkConversation': 'DELETE /api/projects/{project_id}/conversations/{conversation_id}',
  'Projects.updateProject': 'PUT /api/projects/{project_id}',
  'Providers.listEnabledProviders': 'GET /api/providers',
  'User.greet': 'POST /api/user/greet',
  'User.updateAccountPassword': 'PUT /api/admin/config/user/password',
  'UserSettings.deleteAllUserSettings': 'DELETE /api/user/settings/all',
  'UserSettings.deleteUserSetting': 'DELETE /api/user/settings/{key}',
  'UserSettings.getUserSetting': 'GET /api/user/settings/{key}',
  'UserSettings.getUserSettings': 'GET /api/user/settings',
  'UserSettings.setUserSetting': 'POST /api/user/settings',
  'Utils.testProxy': 'POST /api/utils/test-proxy'
} as const

// API endpoint parameters
export type ApiEndpointParameters = {
  'Admin.addApiProxyServerTrustedHost': CreateTrustedHostRequest
  'Admin.addDatabaseToRAGProvider': CreateRAGDatabaseRequest
  'Admin.addModelToApiProxyServer': CreateApiProxyServerModelRequest
  'Admin.addModelToProvider': CreateModelRequest
  'Admin.assignProviderToGroup': AssignProviderToGroupRequest
  'Admin.assignUserToGroup': AssignUserToGroupRequest
  'Admin.cancelDownload': { download_id: string }
  'Admin.cloneRAGProvider': { provider_id: string }
  'Admin.createAssistant': CreateAssistantRequest
  'Admin.createGroup': CreateUserGroupRequest
  'Admin.createProvider': CreateProviderRequest
  'Admin.createRAGProvider': CreateRAGProviderRequest
  'Admin.createRAGRepository': CreateRAGRepositoryRequest
  'Admin.createRepository': CreateRepositoryRequest
  'Admin.createUser': CreateUserRequest
  'Admin.deleteAssistant': { assistant_id: string }
  'Admin.deleteDownload': { download_id: string }
  'Admin.deleteGroup': { group_id: string }
  'Admin.deleteModel': { model_id: string }
  'Admin.deleteProvider': { provider_id: string }
  'Admin.deleteRAGDatabase': { database_id: string }
  'Admin.deleteRAGProvider': { provider_id: string }
  'Admin.deleteRAGRepository': { repository_id: string }
  'Admin.deleteRepository': { repository_id: string }
  'Admin.deleteUser': { user_id: string }
  'Admin.disableModel': { model_id: string }
  'Admin.disableRAGDatabase': { database_id: string }
  'Admin.downloadFromRepository': DownloadFromRepositoryRequest
  'Admin.downloadRAGDatabaseFromRepository': DownloadRAGDatabaseFromRepositoryRequest
  'Admin.enableModel': { model_id: string }
  'Admin.enableRAGDatabase': { database_id: string }
  'Admin.getApiProxyServerConfig': void
  'Admin.getApiProxyServerStatus': void
  'Admin.getAssistant': { assistant_id: string }
  'Admin.getAvailableDevices': void
  'Admin.getDefaultLanguage': void
  'Admin.getDownload': { download_id: string }
  'Admin.getGroup': { group_id: string }
  'Admin.getGroupMembers': { group_id: string; page?: number | null; per_page?: number | null }
  'Admin.getGroupProviders': { group_id: string }
  'Admin.getHardwareInfo': void
  'Admin.getModel': { model_id: string }
  'Admin.getNgrokSettings': void
  'Admin.getNgrokStatus': void
  'Admin.getProvider': { provider_id: string }
  'Admin.getProviderGroups': { provider_id: string }
  'Admin.getProxySettings': void
  'Admin.getRAGDatabase': { database_id: string }
  'Admin.getRAGProvider': { provider_id: string }
  'Admin.getRAGRepository': { repository_id: string }
  'Admin.getRepository': { repository_id: string }
  'Admin.getUser': { user_id: string }
  'Admin.getUserRegistrationStatus': void
  'Admin.listAllDownloads': { page?: number | null; per_page?: number | null; status?: string | null }
  'Admin.listApiProxyServerModels': void
  'Admin.listApiProxyServerTrustedHosts': void
  'Admin.listAssistants': { page?: number | null; per_page?: number | null }
  'Admin.listEngines': void
  'Admin.listGroups': { page?: number | null; per_page?: number | null }
  'Admin.listProviderModels': { provider_id: string }
  'Admin.listProviders': { page?: number | null; per_page?: number | null }
  'Admin.listRAGProviderDatabases': { provider_id: string }
  'Admin.listRAGProviders': { page?: number | null; per_page?: number | null }
  'Admin.listRAGRepositories': { page?: number | null; per_page?: number | null }
  'Admin.listRAGRepositoryDatabases': { repository_id: string }
  'Admin.listRepositories': { page?: number | null; per_page?: number | null }
  'Admin.listUserGroupProviderRelationships': void
  'Admin.listUsers': { page?: number | null; per_page?: number | null }
  'Admin.reloadApiProxyServerModels': void
  'Admin.reloadApiProxyServerTrustedHosts': void
  'Admin.removeApiProxyServerTrustedHost': { host_id: string }
  'Admin.removeModelFromApiProxyServer': { model_id: string }
  'Admin.removeProviderFromGroup': { group_id: string; provider_id: string }
  'Admin.removeUserFromGroup': { user_id: string; group_id: string }
  'Admin.resetUserPassword': ResetPasswordRequest
  'Admin.startApiProxyServer': void
  'Admin.startModel': { model_id: string }
  'Admin.startNgrokTunnel': void
  'Admin.startRAGDatabase': { database_id: string }
  'Admin.stopApiProxyServer': void
  'Admin.stopModel': { model_id: string }
  'Admin.stopNgrokTunnel': void
  'Admin.stopRAGDatabase': { database_id: string }
  'Admin.subscribeApiProxyServerLogs': void
  'Admin.subscribeDownloadProgress': void
  'Admin.subscribeHardwareUsage': void
  'Admin.testRAGRepositoryConnection': { repository_id: string }
  'Admin.testRepositoryConnection': TestRepositoryConnectionRequest
  'Admin.toggleUserActive': { user_id: string }
  'Admin.updateApiProxyServerConfig': ApiProxyServerConfig
  'Admin.updateApiProxyServerModel': UpdateApiProxyServerModelRequest
  'Admin.updateApiProxyServerTrustedHost': UpdateTrustedHostRequest
  'Admin.updateAssistant': UpdateAssistantRequest
  'Admin.updateDefaultLanguage': UpdateDefaultLanguageRequest
  'Admin.updateGroup': UpdateUserGroupRequest
  'Admin.updateModel': UpdateModelRequest
  'Admin.updateNgrokSettings': UpdateNgrokSettingsRequest
  'Admin.updateProvider': UpdateProviderRequest
  'Admin.updateProxySettings': UpdateProxySettingsRequest
  'Admin.updateRAGDatabase': UpdateRAGDatabaseRequest
  'Admin.updateRAGProvider': UpdateRAGProviderRequest
  'Admin.updateRAGRepository': UpdateRAGRepositoryRequest
  'Admin.updateRepository': UpdateRepositoryRequest
  'Admin.updateUser': UpdateUserRequest
  'Admin.updateUserRegistrationStatus': UpdateUserRegistrationRequest
  'Admin.uploadAndCommitModel': void
  'Assistants.createAssistant': CreateAssistantRequest
  'Assistants.deleteAssistant': { assistant_id: string }
  'Assistants.getAssistant': { assistant_id: string }
  'Assistants.getDefaultAssistant': void
  'Assistants.listAssistants': { page?: number | null; per_page?: number | null }
  'Assistants.updateAssistant': UpdateAssistantRequest
  'Auth.init': void
  'Auth.login': LoginRequest
  'Auth.logout': void
  'Auth.me': void
  'Auth.register': CreateUserRequest
  'Auth.setup': CreateUserRequest
  'Chat.createConversation': CreateConversationRequest
  'Chat.deleteConversation': { conversation_id: string }
  'Chat.editMessageStream': ChatMessageRequest
  'Chat.getConversation': { conversation_id: string }
  'Chat.getConversationMessagesByBranch': { conversation_id: string; branch_id: string }
  'Chat.getMessageBranches': { message_id: string }
  'Chat.listConversations': { page?: number | null; per_page?: number | null; project_id?: string | null }
  'Chat.searchConversations': { q: string; page?: number | null; per_page?: number | null; project_id?: string | null }
  'Chat.sendMessageStream': ChatMessageRequest
  'Chat.switchConversationBranch': SwitchBranchRequest
  'Chat.updateConversation': UpdateConversationRequest
  'Config.getDefaultLanguage': void
  'Config.getUserRegistrationStatus': void
  'Files.deleteFile': { id: string }
  'Files.downloadFile': { id: string }
  'Files.downloadFileWithToken': { id: string; token?: string | null }
  'Files.generateDownloadToken': { id: string }
  'Files.getFile': { id: string }
  'Files.getFilePreview': { id: string; page?: number | null }
  'Files.listMessageFiles': { id: string }
  'Files.listProjectFiles': { id: string; page?: number | null; per_page?: number | null; search?: string | null }
  'Files.removeFileFromMessage': { file_id: string; message_id: string }
  'Files.uploadFile': void
  'Files.uploadProjectFile': { id: string }
  'Hub.getHubData': { lang?: string | null }
  'Hub.getHubVersion': void
  'Hub.refreshHubData': { lang?: string | null }
  'Models.listEnabledProviderModels': { provider_id: string }
  'Projects.createProject': CreateProjectRequest
  'Projects.deleteProject': { project_id: string }
  'Projects.getProject': { project_id: string }
  'Projects.linkConversation': { project_id: string; conversation_id: string }
  'Projects.listProjects': { page?: number | null; per_page?: number | null; search?: string | null }
  'Projects.unlinkConversation': { project_id: string; conversation_id: string }
  'Projects.updateProject': UpdateProjectRequest
  'Providers.listEnabledProviders': { page?: number | null; per_page?: number | null }
  'User.greet': UserHello
  'User.updateAccountPassword': UpdateUserPasswordRequest
  'UserSettings.deleteAllUserSettings': void
  'UserSettings.deleteUserSetting': { key: string }
  'UserSettings.getUserSetting': { key: string }
  'UserSettings.getUserSettings': void
  'UserSettings.setUserSetting': UserSettingRequest
  'Utils.testProxy': TestProxyConnectionRequest
}

// API endpoint responses
export type ApiEndpointResponses = {
  'Admin.addApiProxyServerTrustedHost': ApiProxyServerTrustedHost
  'Admin.addDatabaseToRAGProvider': RAGDatabase
  'Admin.addModelToApiProxyServer': ApiProxyServerModel
  'Admin.addModelToProvider': Model
  'Admin.assignProviderToGroup': UserGroupProviderResponse
  'Admin.assignUserToGroup': void
  'Admin.cancelDownload': void
  'Admin.cloneRAGProvider': RAGProvider
  'Admin.createAssistant': Assistant
  'Admin.createGroup': UserGroup
  'Admin.createProvider': Provider
  'Admin.createRAGProvider': RAGProvider
  'Admin.createRAGRepository': RAGRepository
  'Admin.createRepository': Repository
  'Admin.createUser': User
  'Admin.deleteAssistant': void
  'Admin.deleteDownload': void
  'Admin.deleteGroup': void
  'Admin.deleteModel': void
  'Admin.deleteProvider': void
  'Admin.deleteRAGDatabase': void
  'Admin.deleteRAGProvider': void
  'Admin.deleteRAGRepository': void
  'Admin.deleteRepository': void
  'Admin.deleteUser': void
  'Admin.disableModel': void
  'Admin.disableRAGDatabase': void
  'Admin.downloadFromRepository': DownloadInstance
  'Admin.downloadRAGDatabaseFromRepository': RAGDatabase
  'Admin.enableModel': void
  'Admin.enableRAGDatabase': void
  'Admin.getApiProxyServerConfig': ApiProxyServerConfig
  'Admin.getApiProxyServerStatus': ApiProxyServerStatus
  'Admin.getAssistant': Assistant
  'Admin.getAvailableDevices': AvailableDevicesResponse
  'Admin.getDefaultLanguage': DefaultLanguageResponse
  'Admin.getDownload': void
  'Admin.getGroup': UserGroup
  'Admin.getGroupMembers': UserListResponse
  'Admin.getGroupProviders': Provider[]
  'Admin.getHardwareInfo': HardwareInfoResponse
  'Admin.getModel': Model
  'Admin.getNgrokSettings': NgrokSettingsResponse
  'Admin.getNgrokStatus': NgrokStatusResponse
  'Admin.getProvider': Provider
  'Admin.getProviderGroups': UserGroup[]
  'Admin.getProxySettings': ProxySettingsResponse
  'Admin.getRAGDatabase': RAGDatabase
  'Admin.getRAGProvider': RAGProvider
  'Admin.getRAGRepository': RAGRepository
  'Admin.getRepository': Repository
  'Admin.getUser': User
  'Admin.getUserRegistrationStatus': UserRegistrationStatusResponse
  'Admin.listAllDownloads': void
  'Admin.listApiProxyServerModels': ApiProxyServerModel[]
  'Admin.listApiProxyServerTrustedHosts': ApiProxyServerTrustedHost[]
  'Admin.listAssistants': AssistantListResponse
  'Admin.listEngines': EngineInfo[]
  'Admin.listGroups': UserGroupListResponse
  'Admin.listProviderModels': Model[]
  'Admin.listProviders': ProviderListResponse
  'Admin.listRAGProviderDatabases': RAGDatabase[]
  'Admin.listRAGProviders': RAGProviderListResponse
  'Admin.listRAGRepositories': RAGRepositoryListResponse
  'Admin.listRAGRepositoryDatabases': RAGDatabase[]
  'Admin.listRepositories': RepositoryListResponse
  'Admin.listUserGroupProviderRelationships': UserGroupProviderResponse[]
  'Admin.listUsers': UserListResponse
  'Admin.reloadApiProxyServerModels': void
  'Admin.reloadApiProxyServerTrustedHosts': void
  'Admin.removeApiProxyServerTrustedHost': void
  'Admin.removeModelFromApiProxyServer': void
  'Admin.removeProviderFromGroup': void
  'Admin.removeUserFromGroup': void
  'Admin.resetUserPassword': void
  'Admin.startApiProxyServer': void
  'Admin.startModel': void
  'Admin.startNgrokTunnel': NgrokStatusResponse
  'Admin.startRAGDatabase': void
  'Admin.stopApiProxyServer': void
  'Admin.stopModel': void
  'Admin.stopNgrokTunnel': NgrokStatusResponse
  'Admin.stopRAGDatabase': void
  'Admin.subscribeApiProxyServerLogs': void
  'Admin.subscribeDownloadProgress': void
  'Admin.subscribeHardwareUsage': void
  'Admin.testRAGRepositoryConnection': RAGRepositoryConnectionTestResponse
  'Admin.testRepositoryConnection': TestRepositoryConnectionResponse
  'Admin.toggleUserActive': UserActiveStatusResponse
  'Admin.updateApiProxyServerConfig': ApiProxyServerConfig
  'Admin.updateApiProxyServerModel': ApiProxyServerModel
  'Admin.updateApiProxyServerTrustedHost': ApiProxyServerTrustedHost
  'Admin.updateAssistant': Assistant
  'Admin.updateDefaultLanguage': DefaultLanguageResponse
  'Admin.updateGroup': UserGroup
  'Admin.updateModel': Model
  'Admin.updateNgrokSettings': NgrokSettingsResponse
  'Admin.updateProvider': Provider
  'Admin.updateProxySettings': ProxySettingsResponse
  'Admin.updateRAGDatabase': RAGDatabase
  'Admin.updateRAGProvider': RAGProvider
  'Admin.updateRAGRepository': RAGRepository
  'Admin.updateRepository': Repository
  'Admin.updateUser': User
  'Admin.updateUserRegistrationStatus': UserRegistrationStatusResponse
  'Admin.uploadAndCommitModel': Model
  'Assistants.createAssistant': Assistant
  'Assistants.deleteAssistant': void
  'Assistants.getAssistant': Assistant
  'Assistants.getDefaultAssistant': Assistant
  'Assistants.listAssistants': AssistantListResponse
  'Assistants.updateAssistant': Assistant
  'Auth.init': InitResponse
  'Auth.login': AuthResponse
  'Auth.logout': void
  'Auth.me': User
  'Auth.register': AuthResponse
  'Auth.setup': AuthResponse
  'Chat.createConversation': Conversation
  'Chat.deleteConversation': void
  'Chat.editMessageStream': void
  'Chat.getConversation': Conversation
  'Chat.getConversationMessagesByBranch': void
  'Chat.getMessageBranches': void
  'Chat.listConversations': ConversationListResponse
  'Chat.searchConversations': void
  'Chat.sendMessageStream': void
  'Chat.switchConversationBranch': OperationSuccessResponse
  'Chat.updateConversation': Conversation
  'Config.getDefaultLanguage': DefaultLanguageResponse
  'Config.getUserRegistrationStatus': UserRegistrationStatusResponse
  'Files.deleteFile': FileOperationSuccessResponse
  'Files.downloadFile': void
  'Files.downloadFileWithToken': void
  'Files.generateDownloadToken': DownloadTokenResponse
  'Files.getFile': File
  'Files.getFilePreview': void
  'Files.listMessageFiles': File[]
  'Files.listProjectFiles': FileListResponse
  'Files.removeFileFromMessage': FileOperationSuccessResponse
  'Files.uploadFile': UploadFileResponse
  'Files.uploadProjectFile': UploadFileResponse
  'Hub.getHubData': HubData
  'Hub.getHubVersion': HubVersionResponse
  'Hub.refreshHubData': HubData
  'Models.listEnabledProviderModels': Model[]
  'Projects.createProject': Project
  'Projects.deleteProject': void
  'Projects.getProject': ProjectDetailResponse
  'Projects.linkConversation': Conversation
  'Projects.listProjects': ProjectListResponse
  'Projects.unlinkConversation': void
  'Projects.updateProject': Project
  'Providers.listEnabledProviders': ProviderListResponse
  'User.greet': string
  'User.updateAccountPassword': void
  'UserSettings.deleteAllUserSettings': UserSettingsDeletionResponse
  'UserSettings.deleteUserSetting': void
  'UserSettings.getUserSetting': UserSetting
  'UserSettings.getUserSettings': UserSettingsResponse
  'UserSettings.setUserSetting': UserSetting
  'Utils.testProxy': TestProxyConnectionResponse
}

// Type helpers
export type ApiEndpoint = keyof typeof ApiEndpoints
export type ApiEndpointUrl = (typeof ApiEndpoints)[ApiEndpoint]

// Extract endpoint key from URL pattern
export function getEndpointKey(url: string): ApiEndpoint | undefined {
  const entries = Object.entries(ApiEndpoints) as [ApiEndpoint, string][]
  const found = entries.find(([_key, value]) => value === url)
  return found ? found[0] : undefined
}

// Get parameter type for endpoint
export type GetParameterType<K extends ApiEndpoint> = ApiEndpointParameters[K]

// Get response type for endpoint  
export type GetResponseType<K extends ApiEndpoint> = ApiEndpointResponses[K]

// Create reverse mapping from URL to endpoint key
export type UrlToEndpoint<U extends ApiEndpointUrl> = {
  [K in keyof typeof ApiEndpoints]: (typeof ApiEndpoints)[K] extends U
    ? K
    : never
}[keyof typeof ApiEndpoints]

// Helper types to get parameter and response types by URL
export type ParameterByUrl<U extends ApiEndpointUrl> =
  ApiEndpointParameters[UrlToEndpoint<U>]
export type ResponseByUrl<U extends ApiEndpointUrl> =
  ApiEndpointResponses[UrlToEndpoint<U>]

// Type-safe validation - this will cause a TypeScript error if any endpoint is missing
type ValidateParametersComplete = {
  [K in keyof typeof ApiEndpoints]: K extends keyof ApiEndpointParameters
    ? true
    : false
}

type ValidateResponsesComplete = {
  [K in keyof typeof ApiEndpoints]: K extends keyof ApiEndpointResponses
    ? true
    : false
}

// Type-safe validation - these will cause a TypeScript error if any endpoint is missing
// from Parameters or Responses. They are used for compile-time validation only.
export type { ValidateParametersComplete, ValidateResponsesComplete }
