/**
 * Generated API endpoint definitions
 * Auto-generated from OpenAPI specification
 * 
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY ⚠️
 * This file is automatically generated from the OpenAPI specification generated from the server code.
 */

// =============================================================================
// TYPE DEFINITIONS
// =============================================================================

export interface ApiProxyServerConfig {
  address: string
  allow_cors: boolean
  api_key: string
  autostart_on_startup: boolean
  log_level: string
  port: number
  prefix: string
}

export interface ApiProxyServerModel {
  alias_id?: string
  created_at: string
  enabled: boolean
  id: string
  is_default: boolean
  model_id: string
  updated_at: string
}

export interface ApiProxyServerStatus {
  active_models: number
  running: boolean
  server_url?: string
}

export interface ApiProxyServerTrustedHost {
  description?: string
  created_at: string
  enabled: boolean
  host: string
  id: string
  updated_at: string
}

export interface ApprovalCheckResponse {
  approved: boolean
  expires_at?: string
  source?: string
}

export interface AssignServersRequest {
  server_ids: string[]
}

export interface AssignUserToGroupRequest {
  group_id: string
  user_id: string
}

export interface Assistant {
  description?: string
  created_at: string
  created_by?: string
  id: string
  instructions?: string
  is_active: boolean
  is_default: boolean
  is_template: boolean
  name: string
  parameters?: ModelParameters
  updated_at: string
}

export interface AssistantListResponse {
  assistants: Assistant[]
  page: number
  per_page: number
  total: number
}

export interface AuthResponse {
  expires_at: string
  token: string
  user: User
}

export interface AvailableDevicesResponse {
  default_device_type: DeviceType
  devices: DeviceInfo[]
  supports_multi_gpu: boolean
}

export interface CPUInfo {
  architecture: string
  base_frequency?: number
  cores: number
  max_frequency?: number
  model: string
  threads?: number
}

export interface CPUUsage {
  frequency?: number
  temperature?: number
  usage_percentage: number
}

export interface CancelExecutionRequest {
  reason?: string
}

export interface ChatMessageRequest {
  assistant_id: string
  content: string
  conversation_id: string
  enabled_rag_ids?: string[]
  enabled_tools?: EnabledMCPTool[]
  file_ids?: string[]
  message_id?: string
  model_id: string
}

export type CompleteData = any

export type ConnectedData = any

export interface Conversation {
  title: string
  active_branch_id?: string
  assistant_id?: string
  created_at: string
  id: string
  model_id?: string
  project_id?: string
  updated_at: string
  user_id: string
}

export interface ConversationListResponse {
  conversations: ConversationSummary[]
  page: number
  per_page: number
  total: number
}

export interface ConversationPaginationQuery {
  page?: number
  per_page?: number
  project_id?: string
}

export interface ConversationSummary {
  title: string
  assistant_id?: string
  created_at: string
  id: string
  last_message?: string
  message_count: number
  model_id?: string
  project_id?: string
  updated_at: string
  user_id: string
}

export interface CreateApiProxyServerModelRequest {
  alias_id?: string
  enabled?: boolean
  is_default?: boolean
  model_id: string
}

export interface CreateAssistantRequest {
  description?: string
  instructions?: string
  is_default?: boolean
  is_template?: boolean
  name: string
  parameters?: ModelParameters
}

export interface CreateConversationApprovalRequest {
  approval_message_content_id?: string
  approved: boolean
  expires_at?: string
  notes?: string
  server_id: string
  tool_name: string
}

export interface CreateConversationRequest {
  title: string
  assistant_id: string
  model_id: string
  project_id?: string
}

export interface CreateMCPServerRequest {
  description?: string
  args?: any
  command?: string
  display_name: string
  enabled?: boolean
  environment_variables?: any
  headers?: any
  max_restart_attempts?: number
  name: string
  timeout_seconds?: number
  transport_type: MCPTransportType
  url?: string
}

export interface CreateModelRequest {
  description?: string
  capabilities?: ModelCapabilities
  display_name: string
  enabled?: boolean
  engine_settings?: ModelEngineSettings
  engine_type: EngineType
  file_format: FileFormat
  name: string
  parameters?: ModelParameters
  provider_id: string
  source?: SourceInfo
}

export interface CreateProjectRequest {
  description?: string
  instruction?: string
  name: string
}

export interface CreateProviderRequest {
  type: string
  api_key?: string
  base_url?: string
  enabled?: boolean
  name: string
  proxy_settings?: ProxySettings
}

export interface CreateRAGInstanceRequest {
  description?: string
  display_name: string
  embedding_model_id?: string
  engine_settings?: RAGEngineSettings
  engine_type: RAGEngineType
  llm_model_id?: string
  name: string
  parameters?: any
  project_id?: string
  provider_id: string
}

export interface CreateRAGProviderRequest {
  type: string
  api_key?: string
  base_url?: string
  can_user_create_instance?: boolean
  enabled?: boolean
  name: string
}

export interface CreateRAGRepositoryRequest {
  description?: string
  auth_token?: string
  enabled?: boolean
  name: string
  priority?: number
  requires_auth?: boolean
  url: string
}

export interface CreateRepositoryRequest {
  auth_config?: RepositoryAuthConfig
  auth_type: string
  enabled?: boolean
  name: string
  url: string
}

export interface CreateSystemMCPServerRequest {
  description?: string
  args?: any
  command?: string
  display_name: string
  enabled?: boolean
  environment_variables?: any
  headers?: any
  max_restart_attempts?: number
  name: string
  timeout_seconds?: number
  transport_type: MCPTransportType
  url?: string
}

export interface CreateSystemRAGInstanceRequest {
  description?: string
  display_name: string
  embedding_model_id?: string
  engine_settings?: RAGEngineSettings
  engine_type: RAGEngineType
  llm_model_id?: string
  name: string
  parameters?: any
  provider_id: string
}

export interface CreateTrustedHostRequest {
  description?: string
  enabled?: boolean
  host: string
}

export interface CreateUserGroupRequest {
  description?: string
  mcp_server_ids?: string[]
  name: string
  permissions: string[]
  provider_ids?: string[]
  rag_provider_ids?: string[]
}

export interface CreateUserRequest {
  email: string
  password: string
  profile?: any
  username: string
}

export interface DefaultLanguageResponse {
  language: string
}

export interface DeleteConversationApprovalQuery {
  server_id: string
  tool_name: string
}

export interface DeviceInfo {
  device_type: DeviceType
  id: number
  is_available: boolean
  memory_free?: number
  memory_total?: number
  name: string
}

export type DeviceType = string | string | string | string | string | string | string

export interface DownloadFromRepositoryRequest {
  description?: string
  capabilities?: ModelCapabilities
  display_name: string
  engine_settings?: ModelEngineSettings
  engine_type?: EngineType
  file_format: FileFormat
  main_filename: string
  name: string
  parameters?: ModelParameters
  provider_id: string
  repository_branch?: string
  repository_id: string
  repository_path: string
  source: SourceInfo
}

export interface DownloadInstance {
  completed_at?: string
  created_at: string
  error_message?: string
  id: string
  model_id?: string
  progress_data?: DownloadProgressData
  provider_id: string
  repository_id: string
  request_data: DownloadRequestData
  started_at: string
  status: DownloadStatus
  updated_at: string
}

export interface DownloadInstanceListResponse {
  downloads: DownloadInstance[]
  page: number
  per_page: number
  total: number
}

export interface DownloadPaginationQuery {
  page?: number
  per_page?: number
  status?: string
}

export type DownloadPhase = 'created' | 'connecting' | 'analyzing' | 'downloading' | 'receiving' | 'resolving' | 'checkingout' | 'committing' | 'complete' | 'error'

export interface DownloadProgressData {
  current: number
  eta_seconds: number
  message: string
  phase: DownloadPhase
  speed_bps: number
  total: number
}

export interface DownloadProgressUpdate {
  current?: number
  error_message?: string
  eta_seconds?: number
  id: string
  message?: string
  phase: DownloadPhase
  speed_bps?: number
  status: string
  total?: number
}

export interface DownloadRequestData {
  description?: string
  capabilities?: ModelCapabilities
  display_name?: string
  engine_settings?: ModelEngineSettings
  engine_type?: EngineType
  file_format?: string
  files?: string[]
  main_filename?: string
  model_name: string
  parameters?: ModelParameters
  quantization?: string
  repository_path?: string
  revision?: string
  source?: SourceInfo
}

export type DownloadStatus = 'pending' | 'downloading' | 'completed' | 'failed' | 'cancelled'

export interface DownloadTokenParams {
  token?: string
}

export interface DownloadTokenResponse {
  expires_at: string
  token: string
}

export interface EnabledMCPTool {
  name: string
  server_id: string
}

export interface EngineInfo {
  engine_type: EngineType
  name: string
  status: string
  supported_architectures?: string[]
  version: string
}

export type EngineType = 'mistralrs' | 'llamacpp' | 'none'

export interface ExecuteToolRequest {
  auto_approve?: boolean
  conversation_id?: string
  parameters: any
  server_id?: string
  tool_name: string
}

export interface File {
  checksum?: string
  created_at: string
  file_size: number
  filename: string
  id: string
  mime_type?: string
  page_count: number
  processing_metadata: any
  project_id?: string
  thumbnail_count: number
  updated_at: string
  user_id: string
}

export type FileFormat = 'safetensors' | 'pytorch' | 'gguf'

export interface FileListParams {
  page?: number
  per_page?: number
  search?: string
}

export interface FileListResponse {
  files: File[]
  page: number
  per_page: number
  total: number
}

export interface FileOperationSuccessResponse {
  success: boolean
}

export interface FindToolQuery {
  server_id?: string
}

export interface GPUComputeCapabilities {
  cuda_support: boolean
  cuda_version?: string
  metal_support: boolean
  opencl_support: boolean
  vulkan_support?: boolean
}

export interface GPUDevice {
  compute_capabilities: GPUComputeCapabilities
  device_id: string
  driver_version?: string
  memory?: number
  name: string
  vendor: string
}

export interface GPUUsage {
  device_id: string
  device_name: string
  memory_total?: number
  memory_usage_percentage?: number
  memory_used?: number
  power_usage?: number
  temperature?: number
  utilization_percentage?: number
}

export interface GroupAssignmentResponse {
  group_id: string
  server_ids: string[]
}

export interface GroupServerAssignment {
  assigned_at: string
  assigned_by_name: string
  server_display_name: string
  server_id: string
  server_name: string
}

export interface GroupServerAssignmentResponse {
  group_id: string
  group_name: string
  server_assignments: GroupServerAssignment[]
}

export interface HardwareInfo {
  cpu: CPUInfo
  gpu_devices: GPUDevice[]
  memory: MemoryInfo
  operating_system: OperatingSystemInfo
}

export interface HardwareInfoResponse {
  hardware: HardwareInfo
}

export interface HardwareUsageUpdate {
  cpu: CPUUsage
  gpu_devices: GPUUsage[]
  memory: MemoryUsage
  timestamp: string
}

export interface HubAssistant {
  description?: string
  author?: string
  capabilities_required: string[]
  category: string
  example_prompts?: string[]
  id: string
  instructions?: string
  name: string
  parameters?: any
  popularity_score?: number
  recommended_models: string[]
  tags: string[]
  use_cases?: string[]
}

export interface HubModel {
  description?: string
  capabilities?: ModelCapabilities
  context_length?: number
  display_name: string
  file_format: FileFormat
  id: string
  language_support?: string[]
  license?: string
  main_filename: string
  name: string
  popularity_score?: number
  public: boolean
  quantization_options?: HubModelQuantizationOption[]
  recommended_engine?: EngineType
  recommended_engine_settings?: any
  recommended_parameters?: any
  repository_path: string
  repository_url: string
  size_gb: number
  tags: string[]
}

export interface HubModelQuantizationOption {
  main_filename: string
  name: string
}

export interface HubQueryParams {
  lang?: string
}

export interface HubVersionResponse {
  hub_version: string
}

export interface InitResponse {
  allow_registration: boolean
  is_desktop: boolean
  needs_setup: boolean
  token?: string
}

export interface ListConversationApprovalsQuery {
  approved?: boolean
  include_expired?: boolean
  page?: number
  per_page?: number
  server_id?: string
  tool_name?: string
}

export interface ListExecutionLogsQuery {
  page?: number
  per_page?: number
  server_id?: string
  status?: string
  thread_id?: string
}

export interface ListExecutionLogsResponse {
  logs: MCPExecutionLog[]
  page: number
  per_page: number
  total: number
}

export interface ListServersQuery {
  page?: number
  per_page?: number
  status?: string
}

export interface ListServersResponse {
  page: number
  per_page: number
  servers: MCPServer[]
  total: number
}

export interface ListSystemServersQuery {
  enabled?: boolean
  page?: number
  per_page?: number
}

export interface ListToolsQuery {
  page?: number
  per_page?: number
  search?: string
  server_id?: string
}

export interface ListToolsResponse {
  page: number
  per_page: number
  tools: MCPToolWithServer[]
  total: number
}

export interface LlamaCppSettings {
  batch_size?: number
  cache_type_k?: string
  cache_type_v?: string
  cont_batching?: boolean
  ctx_size?: number
  device_ids?: number[]
  device_type?: DeviceType
  flash_attn?: boolean
  keep?: number
  main_gpu?: number
  mlock?: boolean
  n_gpu_layers?: number
  no_kv_offload?: boolean
  no_mmap?: boolean
  numa?: string
  parallel?: number
  rope_freq_base?: number
  rope_freq_scale?: number
  rope_scaling?: string
  seed?: number
  split_mode?: string
  tensor_split?: string
  threads?: number
  threads_batch?: number
  ubatch_size?: number
}

export interface LoginRequest {
  password: string
  username_or_email: string
}

export interface MCPExecutionLog {
  completed_at?: string
  correlation_id?: string
  duration_ms?: number
  error_code?: string
  error_message?: string
  execution_result?: any
  id: string
  request_id?: string
  server_id: string
  started_at: string
  status: MCPExecutionStatus
  thread_id?: string
  tool_name: string
  tool_parameters?: any
  user_id: string
}

export type MCPExecutionStatus = 'pending' | 'running' | 'completed' | 'failed' | 'cancelled' | 'timeout'

export interface MCPInitialLogsComplete {
  server_id: string
  timestamp: string
}

export interface MCPLogConnectionInfo {
  connected_at: string
  initial_log_count: number
  server_id: string
  server_name: string
}

export interface MCPLogEntry {
  level: string
  log_type: MCPLogType
  message: string
  server_id: string
  timestamp: string
}

export interface MCPLogError {
  error: string
  server_id: string
}

export type MCPLogType = 'Exec' | 'In' | 'Out' | 'Err'

export interface MCPServer {
  description?: string
  args: any
  command?: string
  created_at: string
  display_name: string
  enabled: boolean
  environment_variables: any
  headers: any
  id: string
  is_active: boolean
  is_system: boolean
  last_health_check?: string
  last_restart_at?: string
  max_restart_attempts?: number
  name: string
  port?: number
  process_id?: number
  restart_count: number
  status: MCPServerStatus
  timeout_seconds?: number
  tool_count?: number
  tools_discovered_at?: string
  transport_type: MCPTransportType
  updated_at: string
  url?: string
  user_id?: string
}

export type MCPServerStatus = 'stopped' | 'starting' | 'running' | 'error' | 'restarting'

export interface MCPTool {
  discovered_at: string
  id: string
  input_schema: any
  last_used_at?: string
  server_id: string
  tool_description?: string
  tool_name: string
  usage_count: number
}

export interface MCPToolWithApproval {
  approval_expires_at?: string
  approval_source?: string
  discovered_at: string
  id: string
  input_schema: any
  is_auto_approved: boolean
  last_used_at?: string
  server_id: string
  tool_description?: string
  tool_name: string
  usage_count: number
}

export interface MCPToolWithServer {
  discovered_at: string
  global_approval_expires_at?: string
  global_approval_notes?: string
  global_auto_approve?: boolean
  id: string
  input_schema: any
  is_system: boolean
  last_used_at?: string
  server_display_name: string
  server_id: string
  server_name: string
  tool_description?: string
  tool_name: string
  transport_type: string
  usage_count: number
}

export type MCPTransportType = 'stdio' | 'http' | 'sse'

export interface MaxIterationReachedData {
  iteration: number
}

export interface MemoryInfo {
  total_ram: number
  total_swap?: number
}

export interface MemoryUsage {
  available_ram: number
  available_swap?: number
  usage_percentage: number
  used_ram: number
  used_swap?: number
}

export interface Message {
  contents: MessageContentItem[]
  conversation_id: string
  created_at: string
  edit_count: number
  files: MessageFiles
  id: string
  metadata?: MessageMetadataStruct
  originated_from_id: string
  role: string
  updated_at: string
}

export interface MessageBranch {
  conversation_id: string
  created_at: string
  id: string
  is_clone: boolean
}

export interface MessageContentChunkData {
  delta: string
  message_content_id: string
}

export interface MessageContentDataText {
  text: string
}
export interface MessageContentDataToolCall {
  arguments: any
  call_id: string
  server_id: string
  tool_name: string
}
export interface MessageContentDataToolCallPendingApproval {
  arguments: any
  is_approved?: boolean | null
  server_id: string
  tool_name: string
}
export interface MessageContentDataToolCallPendingApprovalCancel {
  server_id: string
  tool_name: string
}
export interface MessageContentDataToolResult {
  call_id: string
  error_message?: string | null
  result: any
  success: boolean
}
export interface MessageContentDataFileAttachment {
  file_id: string
  file_type?: string | null
  filename: string
}
export interface MessageContentDataError {
  details?: any
  error_type: string
  message: string
}

export type MessageContentData = MessageContentDataText | MessageContentDataToolCall | MessageContentDataToolCallPendingApproval | MessageContentDataToolCallPendingApprovalCancel | MessageContentDataToolResult | MessageContentDataFileAttachment | MessageContentDataError

export interface MessageContentItem {
  content: MessageContentData
  content_type: MessageContentType
  created_at: string
  id: string
  message_id: string
  sequence_order: number
  updated_at: string
}

export type MessageContentType = 'text' | 'tool_call' | 'tool_call_pending_approval' | 'tool_call_pending_approval_cancel' | 'tool_result' | 'file_attachment' | 'error'

export type MessageFiles = File[]

export interface MessageMetadataStruct {
  enabled_rag_ids?: string[]
  enabled_tools?: EnabledMCPTool[]
}

export type MistralRsCommand = string | string | string | string | string | string | string

export interface MistralRsSettings {
  arch?: string
  chat_template?: string
  command?: MistralRsCommand
  cpu?: boolean
  device_ids?: number[]
  device_type?: DeviceType
  dtype?: string
  enable_search?: boolean
  enable_thinking?: boolean
  in_situ_quant?: string
  interactive_mode?: boolean
  jinja_explicit?: string
  log_file?: string
  max_edge?: number
  max_image_length?: number
  max_num_images?: number
  max_seq_len?: number
  max_seqs?: number
  model_id_name?: string
  no_kv_cache?: boolean
  no_paged_attn?: boolean
  num_device_layers?: string[]
  paged_attn?: boolean
  paged_attn_block_size?: number
  paged_attn_gpu_mem?: number
  paged_attn_gpu_mem_usage?: number
  paged_ctxt_len?: number
  prefix_cache_n?: number
  prompt_chunksize?: number
  quantized_filename?: string
  search_bert_model?: string
  seed?: number
  serve_ip?: string
  token_source?: string
  tokenizer_json?: string
  truncate_sequence?: boolean
  weight_file?: string
}

export interface Model {
  description?: string
  capabilities?: ModelCapabilities
  created_at: string
  display_name: string
  embedding_dimension?: number
  enabled: boolean
  engine_settings?: ModelEngineSettings
  engine_type: EngineType
  file_format: FileFormat
  file_size_bytes?: number
  id: string
  is_active: boolean
  is_deprecated: boolean
  name: string
  parameters?: ModelParameters
  pid?: number
  port?: number
  provider_id: string
  source?: SourceInfo
  updated_at: string
  validation_issues?: string[]
  validation_status?: string
}

export interface ModelCapabilities {
  audio?: boolean
  chat?: boolean
  code_interpreter?: boolean
  image_generator?: boolean
  text_embedding?: boolean
  tools?: boolean
  vision?: boolean
}

export interface ModelEngineSettings {
  llamacpp?: LlamaCppSettings
  mistralrs?: MistralRsSettings
}

export interface ModelParameters {
  frequency_penalty?: number
  max_tokens?: number
  min_p?: number
  presence_penalty?: number
  repeat_last_n?: number
  repeat_penalty?: number
  seed?: number
  stop?: string[]
  temperature?: number
  top_k?: number
  top_p?: number
}

export interface NewAssistantMessageData {
  message_id: string
}

export interface NewMessageContentData {
  message_content_id: string
  message_id: string
}

export interface NewUserMessageData {
  message_id: string
}

export interface NgrokSettingsResponse {
  api_key: string
  auto_start: boolean
  domain?: string
  tunnel_enabled: boolean
  tunnel_status: string
  tunnel_url?: string
}

export interface NgrokStatusResponse {
  last_error?: string
  tunnel_active: boolean
  tunnel_status: string
  tunnel_url?: string
}

export interface OperatingSystemInfo {
  architecture: string
  kernel_version?: string
  name: string
  version: string
}

export interface OperationSuccessResponse {
  message: string
  success: boolean
}

export interface PaginationQuery {
  page?: number
  per_page?: number
}

export interface PasswordService {
  bcrypt: string
  salt: string
}

export enum Permission {
  UsersRead = 'users::read',
  UsersEdit = 'users::edit',
  UsersDelete = 'users::delete',
  UsersCreate = 'users::create',
  UsersResetPassword = 'users::reset-password',
  UsersToggleStatus = 'users::toggle-status',
  GroupsRead = 'groups::read',
  GroupsEdit = 'groups::edit',
  GroupsDelete = 'groups::delete',
  GroupsCreate = 'groups::create',
  GroupsAssignUsers = 'groups::assign-users',
  GroupsAssignProviders = 'groups::assign-providers',
  ChatRead = 'chat::read',
  ChatCreate = 'chat::create',
  ChatEdit = 'chat::edit',
  ChatDelete = 'chat::delete',
  ChatStream = 'chat::stream',
  ChatSearch = 'chat::search',
  ChatBranch = 'chat::branch',
  ProjectsRead = 'projects::read',
  ProjectsCreate = 'projects::create',
  ProjectsEdit = 'projects::edit',
  ProjectsDelete = 'projects::delete',
  FilesRead = 'files::read',
  FilesUpload = 'files::upload',
  FilesDelete = 'files::delete',
  FilesDownload = 'files::download',
  FilesPreview = 'files::preview',
  FilesGenerateToken = 'files::generate-token',
  AssistantsRead = 'assistants::read',
  AssistantsCreate = 'assistants::create',
  AssistantsEdit = 'assistants::edit',
  AssistantsDelete = 'assistants::delete',
  AssistantsAdminRead = 'assistants::admin::read',
  AssistantsAdminCreate = 'assistants::admin::create',
  AssistantsAdminEdit = 'assistants::admin::edit',
  AssistantsAdminDelete = 'assistants::admin::delete',
  SettingsRead = 'settings::read',
  SettingsEdit = 'settings::edit',
  SettingsDelete = 'settings::delete',
  ProvidersRead = 'providers::read',
  ProvidersEdit = 'providers::edit',
  ProvidersDelete = 'providers::delete',
  ProvidersCreate = 'providers::create',
  ProvidersViewGroups = 'providers::view-groups',
  ModelsRead = 'models::read',
  ModelsCreate = 'models::create',
  ModelsEdit = 'models::edit',
  ModelsDelete = 'models::delete',
  ModelsStart = 'models::start',
  ModelsStop = 'models::stop',
  ModelsEnable = 'models::enable',
  ModelsDisable = 'models::disable',
  ModelsUpload = 'models::upload',
  RepositoriesRead = 'repositories::read',
  RepositoriesEdit = 'repositories::edit',
  RepositoriesDelete = 'repositories::delete',
  RepositoriesCreate = 'repositories::create',
  RagProvidersRead = 'rag::providers::read',
  RagProvidersCreate = 'rag::providers::create',
  RagProvidersEdit = 'rag::providers::edit',
  RagProvidersDelete = 'rag::providers::delete',
  RagRepositoriesRead = 'rag::repositories::read',
  RagRepositoriesCreate = 'rag::repositories::create',
  RagRepositoriesEdit = 'rag::repositories::edit',
  RagRepositoriesDelete = 'rag::repositories::delete',
  RagInstancesRead = 'rag::instances::read',
  RagInstancesCreate = 'rag::instances::create',
  RagInstancesEdit = 'rag::instances::edit',
  RagInstancesDelete = 'rag::instances::delete',
  RagFilesRead = 'rag::files::read',
  RagFilesAdd = 'rag::files::add',
  RagFilesRemove = 'rag::files::remove',
  RagAdminProvidersRead = 'rag::admin::providers::read',
  RagAdminProvidersCreate = 'rag::admin::providers::create',
  RagAdminProvidersEdit = 'rag::admin::providers::edit',
  RagAdminProvidersDelete = 'rag::admin::providers::delete',
  RagAdminInstancesRead = 'rag::admin::instances::read',
  RagAdminInstancesCreate = 'rag::admin::instances::create',
  RagAdminInstancesEdit = 'rag::admin::instances::edit',
  RagAdminInstancesDelete = 'rag::admin::instances::delete',
  ModelDownloadsRead = 'model-downloads::read',
  ModelDownloadsCreate = 'model-downloads::create',
  ModelDownloadsCancel = 'model-downloads::cancel',
  ModelDownloadsDelete = 'model-downloads::delete',
  HardwareRead = 'hardware::read',
  HardwareMonitor = 'hardware::monitor',
  DevicesRead = 'devices::read',
  EnginesRead = 'engines::read',
  ApiProxyRead = 'api-proxy::read',
  ApiProxyStart = 'api-proxy::start',
  ApiProxyStop = 'api-proxy::stop',
  ApiProxyConfigure = 'api-proxy::configure',
  ConfigUserRegistrationRead = 'config::user-registration::read',
  ConfigUserRegistrationEdit = 'config::user-registration::edit',
  ConfigAppearanceRead = 'config::appearance::read',
  ConfigAppearanceEdit = 'config::appearance::edit',
  ConfigProxyRead = 'config::proxy::read',
  ConfigProxyEdit = 'config::proxy::edit',
  ConfigNgrokRead = 'config::ngrok::read',
  ConfigNgrokEdit = 'config::ngrok::edit',
  ConfigNgrokStart = 'config::ngrok::start',
  ConfigNgrokStop = 'config::ngrok::stop',
  HubModelsRead = 'hub::models::read',
  HubAssistantsRead = 'hub::assistants::read',
  HubRefresh = 'hub::refresh',
  HubVersionRead = 'hub::version::read',
  McpServersRead = 'mcp::servers::read',
  McpServersCreate = 'mcp::servers::create',
  McpServersEdit = 'mcp::servers::edit',
  McpServersDelete = 'mcp::servers::delete',
  McpToolsRead = 'mcp::tools::read',
  McpToolsExecute = 'mcp::tools::execute',
  McpAdminServersRead = 'mcp::admin::servers::read',
  McpAdminServersCreate = 'mcp::admin::servers::create',
  McpAdminServersEdit = 'mcp::admin::servers::edit',
  McpAdminServersDelete = 'mcp::admin::servers::delete',
  All = '*'
}

export interface PreviewParams {
  page?: number
}

export interface Project {
  description?: string
  created_at: string
  id: string
  instruction?: string
  name: string
  updated_at: string
  user_id: string
}

export interface ProjectDetailResponse {
  conversations: Conversation[]
  project: Project
}

export interface ProjectListQuery {
  page?: number
  per_page?: number
  search?: string
}

export interface ProjectListResponse {
  page: number
  per_page: number
  projects: Project[]
  total: number
}

export interface Provider {
  type: ProviderType
  api_key?: string
  base_url?: string
  built_in: boolean
  created_at: string
  enabled: boolean
  id: string
  name: string
  proxy_settings?: ProxySettings
  updated_at: string
}

export interface ProviderListResponse {
  page: number
  per_page: number
  providers: Provider[]
  total: number
}

export type ProviderType = 'local' | 'openai' | 'anthropic' | 'groq' | 'gemini' | 'mistral' | 'deepseek' | 'huggingface' | 'custom'

export interface ProxySettings {
  enabled?: boolean
  ignore_ssl_certificates?: boolean
  no_proxy?: string
  password?: string
  url?: string
  username?: string
}

export interface ProxySettingsResponse {
  enabled: boolean
  ignore_ssl_certificates: boolean
  no_proxy: string
  password: string
  url: string
  username: string
}

export type RAGChunkSelectionMethod = 'weight' | 'vector'

export interface RAGEngineSettings {
  simple_graph?: RAGSimpleGraphEngineSettings
  simple_vector?: RAGSimpleVectorEngineSettings
}

export type RAGEngineType = 'simple_vector' | 'simple_graph'

export interface RAGFileProcessingStatus {
  error_message?: string
  file_id: string
  filename: string
  stage?: string
  started_at?: string
  status: string
}

export type RAGIndexingErrorCode = 'text_extraction_failed' | 'unsupported_file_format' | 'file_read_error' | 'chunking_failed' | 'embedding_generation_failed' | 'embedding_model_unavailable' | 'index_storage_failed' | 'content_validation_failed' | 'file_too_large' | 'processing_timeout' | 'processing_error' | 'database_error'

export interface RAGInstance {
  description?: string
  age_graph_name?: string
  created_at: string
  display_name: string
  embedding_model_id?: string
  enabled: boolean
  engine_settings: RAGEngineSettings
  engine_type: RAGEngineType
  error_code?: RAGInstanceErrorCode
  id: string
  is_active: boolean
  is_system: boolean
  llm_model_id?: string
  name: string
  parameters: any
  project_id?: string
  provider_id: string
  status?: RAGInstanceStatus
  updated_at: string
  user_id?: string
}

export type RAGInstanceErrorCode = 'embedding_model_not_config' | 'embedding_model_not_found' | 'embedding_model_test_failed' | 'llm_model_not_config' | 'llm_model_not_found' | 'provider_connection_failed' | 'provider_not_found' | 'rag_instance_not_found' | 'indexing_failed' | 'file_processing_failed' | 'database_error' | 'configuration_error'

export interface RAGInstanceFile {
  created_at: string
  file_id: string
  filename: string
  id: string
  processed_at?: string
  processing_error?: RAGIndexingErrorCode
  processing_status: RAGProcessingStatus
  rag_instance_id: string
  rag_metadata: any
  updated_at: string
}

export interface RAGInstanceFilesListResponse {
  files: RAGInstanceFile[]
  page: number
  per_page: number
  total: number
}

export interface RAGInstanceFilesQuery {
  page?: number
  per_page?: number
  search?: string
  status_filter?: RAGProcessingStatus
}

export interface RAGInstanceListQuery {
  include_system?: boolean
  page?: number
  per_page?: number
}

export interface RAGInstanceListResponse {
  instances: RAGInstance[]
  page: number
  per_page: number
  total: number
}

export type RAGInstanceStatus = 'indexing' | 'finished' | 'error'

export type RAGProcessingStatus = 'pending' | 'processing' | 'completed' | 'failed'

export interface RAGProvider {
  type: RAGProviderType
  api_key?: string
  base_url?: string
  built_in: boolean
  can_user_create_instance: boolean
  created_at: string
  enabled: boolean
  id: string
  name: string
  proxy_settings?: ProxySettings
  updated_at: string
}

export interface RAGProviderListResponse {
  page: number
  per_page: number
  providers: RAGProvider[]
  total: number
}

export type RAGProviderType = 'local' | 'lightrag' | 'ragstack' | 'chroma' | 'weaviate' | 'pinecone' | 'custom'

export interface RAGQueryMetadata {
  chunks_filtered: number
  chunks_retrieved: number
  processing_time_ms: number
  rerank_applied: boolean
}

export interface RAGQueryRequest {
  query: string
}

export interface RAGQueryResponse {
  files: File[]
  metadata: RAGQueryMetadata
  results: RAGSource[]
  token_usage: RAGTokenUsage
}

export interface RAGRepository {
  description?: string
  auth_token?: string
  created_at: string
  enabled: boolean
  id: string
  name: string
  priority: number
  requires_auth: boolean
  updated_at: string
  url: string
}

export interface RAGRepositoryConnectionTestResponse {
  available_databases_count?: number
  message: string
  success: boolean
}

export interface RAGRepositoryListResponse {
  page: number
  per_page: number
  repositories: RAGRepository[]
  total: number
}

export interface RAGSimpleGraphEngineSettings {
  indexing?: RAGSimpleGraphIndexingSettings
  querying?: RAGSimpleGraphQueryingSettings
}

export interface RAGSimpleGraphIndexingSettings {
  chunk_overlap_token_size?: number
  chunk_token_size?: number
  entity_extract_max_gleaning?: number
  entity_types?: string[]
  extraction_language?: string
  force_llm_summary_on_merge?: number
  max_graph_nodes?: number
  summary_max_tokens?: number
}

export type RAGSimpleGraphQueryMode = 'local' | 'global' | 'hybrid' | 'naive' | 'mix' | 'bypass'

export interface RAGSimpleGraphQueryingSettings {
  chunk_selection_method?: RAGChunkSelectionMethod
  chunk_top_k?: number
  enable_rerank?: boolean
  max_entity_tokens?: number
  max_graph_nodes_per_query?: number
  max_relation_tokens?: number
  max_total_tokens?: number
  min_rerank_score?: number
  prompt_template_post_query?: string
  prompt_template_pre_query?: string
  query_mode?: RAGSimpleGraphQueryMode
  related_chunk_number?: number
  top_k?: number
}

export interface RAGSimpleVectorEngineSettings {
  indexing?: RAGSimpleVectorIndexingSettings
  querying?: RAGSimpleVectorQueryingSettings
}

export interface RAGSimpleVectorIndexingSettings {
  chunk_overlap_token_size?: number
  chunk_token_size?: number
  embedding_batch_size?: number
  max_parallel_insert?: number
}

export interface RAGSimpleVectorQueryingSettings {
  chunk_selection_method?: RAGChunkSelectionMethod
  chunk_top_k?: number
  enable_rerank?: boolean
  max_total_tokens?: number
  min_rerank_score?: number
  prompt_template_post_query?: string
  prompt_template_pre_query?: string
  related_chunk_number?: number
  similarity_threshold?: number
  top_k?: number
}

export interface RAGSource {
  document: SimpleVectorDocument
  similarity_score: number
}

export interface RAGStatusStreamQuery {
  include_files?: boolean
}

export interface RAGTokenUsage {
  embedding_tokens: number
  max_total_tokens: number
  total_tokens: number
}

export interface Repository {
  auth_config?: RepositoryAuthConfig
  auth_type: string
  built_in: boolean
  created_at: string
  enabled: boolean
  id: string
  name: string
  updated_at: string
  url: string
}

export interface RepositoryAuthConfig {
  api_key?: string
  auth_test_api_endpoint?: string
  password?: string
  token?: string
  username?: string
}

export interface RepositoryListResponse {
  page: number
  per_page: number
  repositories: Repository[]
  total: number
}

export interface ResetPasswordRequest {
  new_password: string
  user_id: string
}

export type SSEChatStreamEvent = {
  connected: ConnectedData
  newUserMessage: NewUserMessageData
  newAssistantMessage: NewAssistantMessageData
  newMessageContent: NewMessageContentData
  messageContentChunk: MessageContentChunkData
  toolCall: ToolCallData
  toolCallPendingApproval: ToolCallPendingApprovalData
  toolCallPendingApprovalCancel: ToolCallPendingApprovalCancelData
  toolResult: ToolResultData
  titleUpdated: TitleUpdatedData
  maxIterationReached: MaxIterationReachedData
  complete: CompleteData
  error: StreamErrorData
  editedMessage: Message
  createdBranch: MessageBranch
}

export interface SSEDownloadProgressConnectedData {
  message?: string
}

export type SSEDownloadProgressEvent = {
  connected: SSEDownloadProgressConnectedData
  update: DownloadProgressUpdate[]
  complete: string
  error: string
}

export interface SSEHardwareUsageConnectedData {
  message: string
}

export type SSEHardwareUsageEvent = {
  connected: SSEHardwareUsageConnectedData
  update: HardwareUsageUpdate
}

export type SSEMCPLogEvent = {
  logEntry: MCPLogEntry
  connected: MCPLogConnectionInfo
  initialLogsComplete: MCPInitialLogsComplete
  error: MCPLogError
}

export interface SSEProxyLogsConnectedData {
  message?: string
}

export type SSEProxyLogsEvent = {
  connected: SSEProxyLogsConnectedData
  logUpdate: SSEProxyLogsUpdateData
}

export interface SSEProxyLogsUpdateData {
  lines: string[]
  timestamp: string
}

export interface SSERAGInstanceStatusConnectedData {
  instance_id: string
}

export interface SSERAGInstanceStatusErrorData {
  error: string
  instance_id: string
}

export interface SSERAGInstanceStatusUpdateData {
  current_files_processing: RAGFileProcessingStatus[]
  enabled: boolean
  error_code?: RAGInstanceErrorCode
  failed_files: number
  instance_id: string
  is_active: boolean
  name: string
  processed_files: number
  processing_files: number
  total_files: number
  updated_at: string
}

export type SSERAGStatusEvent = {
  connected: SSERAGInstanceStatusConnectedData
  update: SSERAGInstanceStatusUpdateData
  error: SSERAGInstanceStatusErrorData
}

export interface SearchQuery {
  page?: number
  per_page?: number
  project_id?: string
  q: string
}

export interface ServerActionResponse {
  message: string
  success: boolean
}

export interface SetToolGlobalApprovalRequest {
  auto_approve: boolean
  expires_at?: string
  notes?: string
}

export interface SimpleResponse {
  message: string
  success: boolean
}

export interface SimpleVectorDocument {
  chunk_index: number
  content: string
  content_hash: string
  created_at: string
  file_id: string
  id: string
  metadata: any
  rag_instance_id: string
  token_count: number
  updated_at: string
}

export interface SourceInfo {
  type: string
  id?: string
}

export interface StreamErrorData {
  code: string
  error: string
}

export interface SwitchBranchRequest {
  branch_id: string
}

export interface TestProxyConnectionRequest {
  enabled: boolean
  ignore_ssl_certificates: boolean
  no_proxy: string
  password: string
  url: string
  username: string
}

export interface TestProxyConnectionResponse {
  message: string
  success: boolean
}

export interface TestRepositoryConnectionRequest {
  auth_config?: RepositoryAuthConfig
  auth_type: string
  name: string
  url: string
}

export interface TestRepositoryConnectionResponse {
  message: string
  success: boolean
}

export interface TitleUpdatedData {
  title: string
}

export interface ToolApprovalResponse {
  approved: boolean
  approved_at?: string
  auto_approve: boolean
  conversation_id?: string
  created_at: string
  expires_at?: string
  id: string
  is_expired: boolean
  is_global: boolean
  notes?: string
  server_id: string
  server_name: string
  tool_name: string
  updated_at: string
  user_id: string
}

export interface ToolCallData {
  arguments: any
  call_id: string
  message_content_id: string
  message_id: string
  server_id: string
  tool_name: string
}

export interface ToolCallPendingApprovalCancelData {
  message_content_id: string
}

export interface ToolCallPendingApprovalData {
  arguments: any
  message_content_id: string
  message_id: string
  server_id: string
  tool_name: string
}

export interface ToolExecutionResponse {
  duration_ms?: number
  error_message?: string
  execution_id: string
  result?: any
  status: MCPExecutionStatus
}

export interface ToolResultData {
  call_id: string
  error_message?: string
  message_content_id: string
  message_id: string
  result: any
  success: boolean
}

export interface UpdateApiProxyServerModelRequest {
  alias_id?: string
  enabled?: boolean
  is_default?: boolean
}

export interface UpdateAssistantRequest {
  description?: string
  instructions?: string
  is_active?: boolean
  is_default?: boolean
  is_template?: boolean
  name?: string
  parameters?: ModelParameters
}

export interface UpdateConversationRequest {
  title?: string
  assistant_id?: string
  model_id?: string
}

export interface UpdateDefaultLanguageRequest {
  language: string
}

export interface UpdateMCPServerRequest {
  description?: string
  args?: any
  command?: string
  display_name?: string
  enabled?: boolean
  environment_variables?: any
  headers?: any
  max_restart_attempts?: number
  timeout_seconds?: number
  url?: string
}

export interface UpdateModelRequest {
  description?: string
  capabilities?: ModelCapabilities
  display_name?: string
  enabled?: boolean
  engine_settings?: ModelEngineSettings
  engine_type?: EngineType
  file_format?: FileFormat
  is_active?: boolean
  name?: string
  parameters?: ModelParameters
}

export interface UpdateNgrokSettingsRequest {
  api_key?: string
  auto_start?: boolean
  domain?: string
  tunnel_enabled?: boolean
}

export interface UpdateProjectRequest {
  description?: string
  instruction?: string
  name?: string
}

export interface UpdateProviderRequest {
  api_key?: string
  base_url?: string
  enabled?: boolean
  name?: string
  proxy_settings?: ProxySettings
}

export interface UpdateProxySettingsRequest {
  enabled: boolean
  ignore_ssl_certificates: boolean
  no_proxy: string
  password: string
  url: string
  username: string
}

export interface UpdateRAGInstanceRequest {
  description?: string
  display_name?: string
  embedding_model_id?: string
  enabled?: boolean
  engine_settings?: RAGEngineSettings
  engine_type?: RAGEngineType
  error_code?: RAGInstanceErrorCode
  is_active?: boolean
  llm_model_id?: string
  name?: string
  parameters?: any
}

export interface UpdateRAGProviderRequest {
  api_key?: string
  base_url?: string
  can_user_create_instance?: boolean
  enabled?: boolean
  name?: string
  proxy_settings?: ProxySettings
}

export interface UpdateRAGRepositoryRequest {
  description?: string
  auth_token?: string
  enabled?: boolean
  name?: string
  priority?: number
  requires_auth?: boolean
  url?: string
}

export interface UpdateRepositoryRequest {
  auth_config?: RepositoryAuthConfig
  auth_type?: string
  enabled?: boolean
  name?: string
  url?: string
}

export interface UpdateToolApprovalRequest {
  approved?: boolean
  auto_approve?: boolean
  expires_at?: string
  notes?: string
}

export interface UpdateTrustedHostRequest {
  description?: string
  enabled?: boolean
  host?: string
}

export interface UpdateUserGroupRequest {
  description?: string
  is_active?: boolean
  mcp_server_ids?: string[]
  name?: string
  permissions?: string[]
  provider_ids?: string[]
  rag_provider_ids?: string[]
}

export interface UpdateUserPasswordRequest {
  current_password?: string
  new_password: string
}

export interface UpdateUserRegistrationRequest {
  enabled: boolean
}

export interface UpdateUserRequest {
  email?: string
  is_active?: boolean
  profile?: any
  username?: string
}

export interface UploadFileResponse {
  file: File
}

export interface User {
  created_at: string
  emails: UserEmail[]
  groups: UserGroup[]
  id: string
  is_active: boolean
  is_protected: boolean
  last_login_at?: string
  profile?: any
  services: UserServices
  updated_at: string
  username: string
}

export interface UserActiveStatusResponse {
  is_active: boolean
}

export interface UserEmail {
  address: string
  created_at: string
  id: string
  user_id: string
  verified: boolean
}

export interface UserGroup {
  description?: string
  created_at: string
  id: string
  is_active: boolean
  is_protected: boolean
  name: string
  permissions: UserGroupPermissions
  updated_at: string
}

export interface UserGroupListResponse {
  groups: UserGroup[]
  page: number
  per_page: number
  total: number
}

export type UserGroupPermissions = string[]

export interface UserHello {
  name: string
}

export interface UserListResponse {
  page: number
  per_page: number
  total: number
  users: User[]
}

export interface UserRegistrationStatusResponse {
  enabled: boolean
}

export interface UserServices {
  password?: PasswordService
}

export interface UserSetting {
  created_at: string
  id: string
  key: string
  updated_at: string
  user_id: string
  value: any
}

export interface UserSettingRequest {
  key: string
  value: any
}

export interface UserSettingsDeletionResponse {
  deleted: number
}

export interface UserSettingsResponse {
  settings: UserSetting[]
}

// =============================================================================
// API ENDPOINTS
// =============================================================================

// API endpoint definitions
export const ApiEndpoints = {
  'Admin.addApiProxyServerTrustedHost': 'POST /api/admin/api-proxy-server/trusted-hosts',
  'Admin.addModelToApiProxyServer': 'POST /api/admin/api-proxy-server/models',
  'Admin.addModelToProvider': 'POST /api/admin/providers/{provider_id}/models',
  'Admin.assignUserToGroup': 'POST /api/admin/groups/assign',
  'Admin.cancelDownload': 'POST /api/admin/downloads/{download_id}/cancel',
  'Admin.createAssistant': 'POST /api/admin/assistants',
  'Admin.createGroup': 'POST /api/admin/groups',
  'Admin.createProvider': 'POST /api/admin/providers',
  'Admin.createRAGRepository': 'POST /api/admin/rag/repositories',
  'Admin.createRagProvider': 'POST /api/admin/rag/providers',
  'Admin.createRepository': 'POST /api/admin/repositories',
  'Admin.createSystemRagInstance': 'POST /api/admin/rag/providers/{provider_id}/instances',
  'Admin.createUser': 'POST /api/admin/users',
  'Admin.deleteAssistant': 'DELETE /api/admin/assistants/{assistant_id}',
  'Admin.deleteDownload': 'DELETE /api/admin/downloads/{download_id}',
  'Admin.deleteGroup': 'DELETE /api/admin/groups/{group_id}',
  'Admin.deleteModel': 'DELETE /api/admin/models/{model_id}',
  'Admin.deleteProvider': 'DELETE /api/admin/providers/{provider_id}',
  'Admin.deleteRAGRepository': 'DELETE /api/admin/rag/repositories/{repository_id}',
  'Admin.deleteRagProvider': 'DELETE /api/admin/rag/providers/{provider_id}',
  'Admin.deleteRepository': 'DELETE /api/admin/repositories/{repository_id}',
  'Admin.deleteSystemRagInstance': 'DELETE /api/admin/rag/instances/{instance_id}',
  'Admin.deleteUser': 'DELETE /api/admin/users/{user_id}',
  'Admin.disableModel': 'POST /api/admin/models/{model_id}/disable',
  'Admin.downloadFromRepository': 'POST /api/admin/models/initiate-repository-download',
  'Admin.enableModel': 'POST /api/admin/models/{model_id}/enable',
  'Admin.getApiProxyServerConfig': 'GET /api/admin/api-proxy-server/config',
  'Admin.getApiProxyServerStatus': 'GET /api/admin/api-proxy-server/status',
  'Admin.getAssistant': 'GET /api/admin/assistants/{assistant_id}',
  'Admin.getAvailableDevices': 'GET /api/admin/devices',
  'Admin.getDefaultLanguage': 'GET /api/admin/config/default-language',
  'Admin.getDownload': 'GET /api/admin/downloads/{download_id}',
  'Admin.getGroup': 'GET /api/admin/groups/{group_id}',
  'Admin.getGroupMcpServers': 'GET /api/admin/groups/{group_id}/mcp_servers',
  'Admin.getGroupMembers': 'GET /api/admin/groups/{group_id}/members',
  'Admin.getGroupProviders': 'GET /api/admin/groups/{group_id}/providers',
  'Admin.getGroupRagProviders': 'GET /api/admin/groups/{group_id}/rag_providers',
  'Admin.getHardwareInfo': 'GET /api/admin/hardware',
  'Admin.getModel': 'GET /api/admin/models/{model_id}',
  'Admin.getNgrokSettings': 'GET /api/admin/config/ngrok',
  'Admin.getNgrokStatus': 'GET /api/admin/config/ngrok/status',
  'Admin.getProvider': 'GET /api/admin/providers/{provider_id}',
  'Admin.getProviderGroups': 'GET /api/admin/providers/{provider_id}/groups',
  'Admin.getProxySettings': 'GET /api/admin/config/proxy',
  'Admin.getRAGRepository': 'GET /api/admin/rag/repositories/{repository_id}',
  'Admin.getRagProvider': 'GET /api/admin/rag/providers/{provider_id}',
  'Admin.getRepository': 'GET /api/admin/repositories/{repository_id}',
  'Admin.getSystemRagInstance': 'GET /api/admin/rag/instances/{instance_id}',
  'Admin.getUser': 'GET /api/admin/users/{user_id}',
  'Admin.getUserRegistrationStatus': 'GET /api/admin/config/user-registration',
  'Admin.listAllDownloads': 'GET /api/admin/downloads',
  'Admin.listApiProxyServerModels': 'GET /api/admin/api-proxy-server/models',
  'Admin.listApiProxyServerTrustedHosts': 'GET /api/admin/api-proxy-server/trusted-hosts',
  'Admin.listAssistants': 'GET /api/admin/assistants',
  'Admin.listEngines': 'GET /api/admin/engines',
  'Admin.listGroups': 'GET /api/admin/groups',
  'Admin.listProviderModels': 'GET /api/admin/providers/{provider_id}/models',
  'Admin.listProviders': 'GET /api/admin/providers',
  'Admin.listRAGRepositories': 'GET /api/admin/rag/repositories',
  'Admin.listRagProviders': 'GET /api/admin/rag/providers',
  'Admin.listRepositories': 'GET /api/admin/repositories',
  'Admin.listSystemRagInstances': 'GET /api/admin/rag/providers/{provider_id}/instances',
  'Admin.listUsers': 'GET /api/admin/users',
  'Admin.reloadApiProxyServerModels': 'POST /api/admin/api-proxy-server/reload/models',
  'Admin.reloadApiProxyServerTrustedHosts': 'POST /api/admin/api-proxy-server/reload/trusted-hosts',
  'Admin.removeApiProxyServerTrustedHost': 'DELETE /api/admin/api-proxy-server/trusted-hosts/{host_id}',
  'Admin.removeModelFromApiProxyServer': 'DELETE /api/admin/api-proxy-server/models/{model_id}',
  'Admin.removeUserFromGroup': 'DELETE /api/admin/groups/{user_id}/{group_id}/remove',
  'Admin.resetUserPassword': 'POST /api/admin/users/reset-password',
  'Admin.startApiProxyServer': 'POST /api/admin/api-proxy-server/start',
  'Admin.startModel': 'POST /api/admin/models/{model_id}/start',
  'Admin.startNgrokTunnel': 'POST /api/admin/config/ngrok/start',
  'Admin.stopApiProxyServer': 'POST /api/admin/api-proxy-server/stop',
  'Admin.stopModel': 'POST /api/admin/models/{model_id}/stop',
  'Admin.stopNgrokTunnel': 'POST /api/admin/config/ngrok/stop',
  'Admin.subscribeApiProxyServerLogs': 'GET /api/admin/api-proxy-server/logs/stream',
  'Admin.subscribeDownloadProgress': 'GET /api/admin/downloads/subscribe',
  'Admin.subscribeHardwareUsage': 'GET /api/admin/hardware/usage-stream',
  'Admin.testRAGRepositoryConnection': 'POST /api/admin/rag/repositories/{repository_id}/test-connection',
  'Admin.testRagProvider': 'POST /api/admin/rag/providers/{provider_id}/test',
  'Admin.testRepositoryConnection': 'POST /api/admin/repositories/test',
  'Admin.toggleUserActive': 'POST /api/admin/users/{user_id}/toggle-active',
  'Admin.updateApiProxyServerConfig': 'PUT /api/admin/api-proxy-server/config',
  'Admin.updateApiProxyServerModel': 'PUT /api/admin/api-proxy-server/models/{model_id}',
  'Admin.updateApiProxyServerTrustedHost': 'PUT /api/admin/api-proxy-server/trusted-hosts/{host_id}',
  'Admin.updateAssistant': 'PUT /api/admin/assistants/{assistant_id}',
  'Admin.updateDefaultLanguage': 'PUT /api/admin/config/default-language',
  'Admin.updateGroup': 'PUT /api/admin/groups/{group_id}',
  'Admin.updateModel': 'PUT /api/admin/models/{model_id}',
  'Admin.updateNgrokSettings': 'PUT /api/admin/config/ngrok',
  'Admin.updateProvider': 'PUT /api/admin/providers/{provider_id}',
  'Admin.updateProxySettings': 'PUT /api/admin/config/proxy',
  'Admin.updateRAGRepository': 'PUT /api/admin/rag/repositories/{repository_id}',
  'Admin.updateRagProvider': 'PUT /api/admin/rag/providers/{provider_id}',
  'Admin.updateRepository': 'PUT /api/admin/repositories/{repository_id}',
  'Admin.updateSystemRagInstance': 'PUT /api/admin/rag/instances/{instance_id}',
  'Admin.updateUser': 'PUT /api/admin/users/{user_id}',
  'Admin.updateUserRegistrationStatus': 'PUT /api/admin/config/user-registration',
  'Admin.uploadAndCommitModel': 'POST /api/admin/uploaded-models/upload-and-commit',
  'AdminMcp.assignServersToGroup': 'POST /api/admin/mcp/groups/{group_id}/servers',
  'AdminMcp.createSystemServer': 'POST /api/admin/mcp/system-servers',
  'AdminMcp.getExecutionStatistics': 'GET /api/admin/mcp/execution/statistics',
  'AdminMcp.getGroupServers': 'GET /api/admin/mcp/groups/{group_id}/servers',
  'AdminMcp.getServerAccessGroups': 'GET /api/admin/mcp/servers/{server_id}/groups',
  'AdminMcp.getToolStatistics': 'GET /api/admin/mcp/tools/statistics',
  'AdminMcp.listAllExecutionLogs': 'GET /api/admin/mcp/execution/logs',
  'AdminMcp.listAllGroupAssignments': 'GET /api/admin/mcp/assignments',
  'AdminMcp.listSystemServers': 'GET /api/admin/mcp/system-servers',
  'AdminMcp.removeServerFromGroup': 'DELETE /api/admin/mcp/groups/{group_id}/servers/{server_id}',
  'Assistants.createAssistant': 'POST /api/assistants',
  'Assistants.deleteAssistant': 'DELETE /api/assistants/{assistant_id}',
  'Assistants.getAssistant': 'GET /api/assistants/{assistant_id}',
  'Assistants.getDefaultAssistant': 'GET /api/assistants/default',
  'Assistants.listAssistants': 'GET /api/assistants',
  'Assistants.updateAssistant': 'PUT /api/assistants/{assistant_id}',
  'Auth.init': 'GET /api/auth/init',
  'Auth.login': 'POST /api/auth/login',
  'Auth.logout': 'POST /api/auth/logout',
  'Auth.me': 'GET /api/auth/me',
  'Auth.register': 'POST /api/auth/register',
  'Auth.setup': 'POST /api/auth/setup',
  'Chat.editMessageStream': 'PUT /api/messages/{message_id}/stream',
  'Chat.getConversationMessagesByBranch': 'GET /api/conversations/{conversation_id}/messages/{branch_id}',
  'Chat.getMessageBranches': 'GET /api/messages/{message_id}/branches',
  'Chat.sendMessageStream': 'POST /api/messages/stream',
  'Config.getDefaultLanguage': 'GET /api/config/default-language',
  'Config.getUserRegistrationStatus': 'GET /api/config/user-registration',
  'Conversation.createConversation': 'POST /api/conversations',
  'Conversation.deleteConversation': 'DELETE /api/conversations/{conversation_id}',
  'Conversation.getConversation': 'GET /api/conversations/{conversation_id}',
  'Conversation.listConversations': 'GET /api/conversations',
  'Conversation.searchConversations': 'GET /api/conversations/search',
  'Conversation.switchConversationBranch': 'PUT /api/conversations/{conversation_id}/branch/switch',
  'Conversation.updateConversation': 'PUT /api/conversations/{conversation_id}',
  'Files.deleteFile': 'DELETE /api/files/{file_id}',
  'Files.downloadFile': 'GET /api/files/{file_id}/download',
  'Files.downloadFileWithToken': 'GET /api/files/{file_id}/download-with-token',
  'Files.generateDownloadToken': 'POST /api/files/{file_id}/download-token',
  'Files.getFile': 'GET /api/files/{file_id}',
  'Files.getFilePreview': 'GET /api/files/{file_id}/preview',
  'Files.listMessageFiles': 'GET /api/messages/{message_id}/files',
  'Files.listProjectFiles': 'GET /api/projects/{project_id}/files',
  'Files.removeFileFromMessage': 'DELETE /api/files/{file_id}/messages/{message_id}',
  'Files.uploadFile': 'POST /api/files/upload',
  'Files.uploadProjectFile': 'POST /api/projects/{project_id}/files',
  'Hub.getHubAssistants': 'GET /api/hub/assistants',
  'Hub.getHubModels': 'GET /api/hub/models',
  'Hub.getHubVersion': 'GET /api/hub/version',
  'Hub.refreshHubData': 'POST /api/hub/refresh',
  'Mcp.cancelExecution': 'POST /api/mcp/execution/logs/{id}/cancel',
  'Mcp.checkConversationApproval': 'GET /api/mcp/approvals/conversations/{conversation_id}/check',
  'Mcp.cleanExpiredApprovals': 'POST /api/mcp/approvals/clean-expired',
  'Mcp.createConversationApproval': 'POST /api/mcp/approvals/conversations/{conversation_id}',
  'Mcp.createServer': 'POST /api/mcp/servers',
  'Mcp.deleteConversationApproval': 'DELETE /api/mcp/approvals/conversations/{conversation_id}/tool',
  'Mcp.deleteServer': 'DELETE /api/mcp/servers/{id}',
  'Mcp.executeTool': 'POST /api/mcp/tools/execute',
  'Mcp.findTool': 'GET /api/mcp/tools/find',
  'Mcp.getExecutionLog': 'GET /api/mcp/execution/logs/{id}',
  'Mcp.getGlobalToolApproval': 'GET /api/mcp/servers/{server_id}/tools/{tool_name}/global-approval',
  'Mcp.getServer': 'GET /api/mcp/servers/{id}',
  'Mcp.getServerTools': 'GET /api/mcp/servers/{id}/tools',
  'Mcp.getUserAssignedServers': 'GET /api/mcp/user/assigned-servers',
  'Mcp.listConversationApprovals': 'GET /api/mcp/approvals/conversations/{conversation_id}',
  'Mcp.listExecutionLogs': 'GET /api/mcp/execution/logs',
  'Mcp.listServers': 'GET /api/mcp/servers',
  'Mcp.listThreadExecutionLogs': 'GET /api/mcp/threads/{thread_id}/execution/logs',
  'Mcp.listTools': 'GET /api/mcp/tools',
  'Mcp.removeToolGlobalApproval': 'DELETE /api/mcp/servers/{server_id}/tools/{tool_name}/approve',
  'Mcp.setToolGlobalApproval': 'POST /api/mcp/servers/{server_id}/tools/{tool_name}/approve',
  'Mcp.startServer': 'POST /api/mcp/servers/{id}/start',
  'Mcp.stopServer': 'POST /api/mcp/servers/{id}/stop',
  'Mcp.streamServerLogs': 'GET /api/mcp/servers/{server_id}/logs/stream',
  'Mcp.updateServer': 'PUT /api/mcp/servers/{id}',
  'Mcp.updateToolApproval': 'PUT /api/mcp/approvals/{approval_id}',
  'Models.listEnabledProviderModels': 'GET /api/providers/{provider_id}/models',
  'Projects.createProject': 'POST /api/projects',
  'Projects.deleteProject': 'DELETE /api/projects/{project_id}',
  'Projects.getProject': 'GET /api/projects/{project_id}',
  'Projects.listProjects': 'GET /api/projects',
  'Projects.updateProject': 'PUT /api/projects/{project_id}',
  'Providers.listEnabledProviders': 'GET /api/providers',
  'Rag.createInstance': 'POST /api/rag/providers/{provider_id}/instances',
  'Rag.deleteInstance': 'DELETE /api/rag/instances/{instance_id}',
  'Rag.deleteInstanceFile': 'DELETE /api/rag/instances/{instance_id}/files/{file_id}',
  'Rag.getInstance': 'GET /api/rag/instances/{instance_id}',
  'Rag.listCreatableProviders': 'GET /api/rag/providers',
  'Rag.listInstanceFiles': 'GET /api/rag/instances/{instance_id}/files',
  'Rag.listInstances': 'GET /api/rag/instances',
  'Rag.queryInstance': 'POST /api/rag/instances/{instance_id}/query',
  'Rag.subscribeInstanceStatus': 'GET /api/rag/instances/{instance_id}/status/stream',
  'Rag.toggleInstanceActivate': 'PUT /api/rag/instances/{instance_id}/toggle-activate',
  'Rag.updateInstance': 'PUT /api/rag/instances/{instance_id}',
  'Rag.uploadInstanceFile': 'POST /api/rag/instances/{instance_id}/files',
  'User.greet': 'POST /api/user/greet',
  'User.updateAccountPassword': 'PUT /api/admin/config/user/password',
  'UserSettings.deleteAllUserSettings': 'DELETE /api/user/settings/all',
  'UserSettings.deleteUserSetting': 'DELETE /api/user/settings/{key}',
  'UserSettings.getUserSetting': 'GET /api/user/settings/{key}',
  'UserSettings.getUserSettings': 'GET /api/user/settings',
  'UserSettings.setUserSetting': 'POST /api/user/settings',
  'Utils.testProxy': 'POST /api/utils/test-proxy'
} as const

// API endpoint parameters
export type ApiEndpointParameters = {
  'Admin.addApiProxyServerTrustedHost': CreateTrustedHostRequest
  'Admin.addModelToApiProxyServer': CreateApiProxyServerModelRequest
  'Admin.addModelToProvider': { provider_id: string } & CreateModelRequest
  'Admin.assignUserToGroup': AssignUserToGroupRequest
  'Admin.cancelDownload': { download_id: string }
  'Admin.createAssistant': CreateAssistantRequest
  'Admin.createGroup': CreateUserGroupRequest
  'Admin.createProvider': CreateProviderRequest
  'Admin.createRAGRepository': CreateRAGRepositoryRequest
  'Admin.createRagProvider': CreateRAGProviderRequest
  'Admin.createRepository': CreateRepositoryRequest
  'Admin.createSystemRagInstance': { provider_id: string } & CreateSystemRAGInstanceRequest
  'Admin.createUser': CreateUserRequest
  'Admin.deleteAssistant': { assistant_id: string }
  'Admin.deleteDownload': { download_id: string }
  'Admin.deleteGroup': { group_id: string }
  'Admin.deleteModel': { model_id: string }
  'Admin.deleteProvider': { provider_id: string }
  'Admin.deleteRAGRepository': { repository_id: string }
  'Admin.deleteRagProvider': { provider_id: string }
  'Admin.deleteRepository': { repository_id: string }
  'Admin.deleteSystemRagInstance': { instance_id: string }
  'Admin.deleteUser': { user_id: string }
  'Admin.disableModel': { model_id: string }
  'Admin.downloadFromRepository': DownloadFromRepositoryRequest
  'Admin.enableModel': { model_id: string }
  'Admin.getApiProxyServerConfig': void
  'Admin.getApiProxyServerStatus': void
  'Admin.getAssistant': { assistant_id: string }
  'Admin.getAvailableDevices': void
  'Admin.getDefaultLanguage': void
  'Admin.getDownload': { download_id: string }
  'Admin.getGroup': { group_id: string }
  'Admin.getGroupMcpServers': { group_id: string }
  'Admin.getGroupMembers': { group_id: string } & PaginationQuery
  'Admin.getGroupProviders': { group_id: string } & PaginationQuery
  'Admin.getGroupRagProviders': { group_id: string } & PaginationQuery
  'Admin.getHardwareInfo': void
  'Admin.getModel': { model_id: string }
  'Admin.getNgrokSettings': void
  'Admin.getNgrokStatus': void
  'Admin.getProvider': { provider_id: string }
  'Admin.getProviderGroups': { provider_id: string }
  'Admin.getProxySettings': void
  'Admin.getRAGRepository': { repository_id: string }
  'Admin.getRagProvider': { provider_id: string }
  'Admin.getRepository': { repository_id: string }
  'Admin.getSystemRagInstance': { instance_id: string }
  'Admin.getUser': { user_id: string }
  'Admin.getUserRegistrationStatus': void
  'Admin.listAllDownloads': { page?: number; per_page?: number; status?: string }
  'Admin.listApiProxyServerModels': void
  'Admin.listApiProxyServerTrustedHosts': void
  'Admin.listAssistants': PaginationQuery
  'Admin.listEngines': void
  'Admin.listGroups': PaginationQuery
  'Admin.listProviderModels': { provider_id: string }
  'Admin.listProviders': PaginationQuery
  'Admin.listRAGRepositories': PaginationQuery
  'Admin.listRagProviders': PaginationQuery
  'Admin.listRepositories': PaginationQuery
  'Admin.listSystemRagInstances': { provider_id: string } & PaginationQuery
  'Admin.listUsers': PaginationQuery
  'Admin.reloadApiProxyServerModels': void
  'Admin.reloadApiProxyServerTrustedHosts': void
  'Admin.removeApiProxyServerTrustedHost': { host_id: string }
  'Admin.removeModelFromApiProxyServer': { model_id: string }
  'Admin.removeUserFromGroup': { user_id: string; group_id: string }
  'Admin.resetUserPassword': ResetPasswordRequest
  'Admin.startApiProxyServer': void
  'Admin.startModel': { model_id: string }
  'Admin.startNgrokTunnel': void
  'Admin.stopApiProxyServer': void
  'Admin.stopModel': { model_id: string }
  'Admin.stopNgrokTunnel': void
  'Admin.subscribeApiProxyServerLogs': void
  'Admin.subscribeDownloadProgress': void
  'Admin.subscribeHardwareUsage': void
  'Admin.testRAGRepositoryConnection': { repository_id: string }
  'Admin.testRagProvider': { provider_id: string }
  'Admin.testRepositoryConnection': TestRepositoryConnectionRequest
  'Admin.toggleUserActive': { user_id: string }
  'Admin.updateApiProxyServerConfig': ApiProxyServerConfig
  'Admin.updateApiProxyServerModel': { model_id: string } & UpdateApiProxyServerModelRequest
  'Admin.updateApiProxyServerTrustedHost': { host_id: string } & UpdateTrustedHostRequest
  'Admin.updateAssistant': { assistant_id: string } & UpdateAssistantRequest
  'Admin.updateDefaultLanguage': UpdateDefaultLanguageRequest
  'Admin.updateGroup': { group_id: string } & UpdateUserGroupRequest
  'Admin.updateModel': { model_id: string } & UpdateModelRequest
  'Admin.updateNgrokSettings': UpdateNgrokSettingsRequest
  'Admin.updateProvider': { provider_id: string } & UpdateProviderRequest
  'Admin.updateProxySettings': UpdateProxySettingsRequest
  'Admin.updateRAGRepository': { repository_id: string } & UpdateRAGRepositoryRequest
  'Admin.updateRagProvider': { provider_id: string } & UpdateRAGProviderRequest
  'Admin.updateRepository': { repository_id: string } & UpdateRepositoryRequest
  'Admin.updateSystemRagInstance': { instance_id: string } & UpdateRAGInstanceRequest
  'Admin.updateUser': { user_id: string } & UpdateUserRequest
  'Admin.updateUserRegistrationStatus': UpdateUserRegistrationRequest
  'Admin.uploadAndCommitModel': FormData
  'AdminMcp.assignServersToGroup': { group_id: string } & AssignServersRequest
  'AdminMcp.createSystemServer': CreateSystemMCPServerRequest
  'AdminMcp.getExecutionStatistics': void
  'AdminMcp.getGroupServers': { group_id: string }
  'AdminMcp.getServerAccessGroups': { server_id: string }
  'AdminMcp.getToolStatistics': void
  'AdminMcp.listAllExecutionLogs': { page?: number; per_page?: number; server_id?: string; status?: string; thread_id?: string }
  'AdminMcp.listAllGroupAssignments': void
  'AdminMcp.listSystemServers': { enabled?: boolean; page?: number; per_page?: number }
  'AdminMcp.removeServerFromGroup': { group_id: string; server_id: string }
  'Assistants.createAssistant': CreateAssistantRequest
  'Assistants.deleteAssistant': { assistant_id: string }
  'Assistants.getAssistant': { assistant_id: string }
  'Assistants.getDefaultAssistant': void
  'Assistants.listAssistants': PaginationQuery
  'Assistants.updateAssistant': { assistant_id: string } & UpdateAssistantRequest
  'Auth.init': void
  'Auth.login': LoginRequest
  'Auth.logout': void
  'Auth.me': void
  'Auth.register': CreateUserRequest
  'Auth.setup': CreateUserRequest
  'Chat.editMessageStream': { message_id: string } & ChatMessageRequest
  'Chat.getConversationMessagesByBranch': { conversation_id: string; branch_id: string }
  'Chat.getMessageBranches': { message_id: string }
  'Chat.sendMessageStream': ChatMessageRequest
  'Config.getDefaultLanguage': void
  'Config.getUserRegistrationStatus': void
  'Conversation.createConversation': CreateConversationRequest
  'Conversation.deleteConversation': { conversation_id: string }
  'Conversation.getConversation': { conversation_id: string }
  'Conversation.listConversations': { page?: number; per_page?: number; project_id?: string }
  'Conversation.searchConversations': { page?: number; per_page?: number; project_id?: string; q: string }
  'Conversation.switchConversationBranch': { conversation_id: string } & SwitchBranchRequest
  'Conversation.updateConversation': { conversation_id: string } & UpdateConversationRequest
  'Files.deleteFile': { file_id: string }
  'Files.downloadFile': { file_id: string }
  'Files.downloadFileWithToken': { file_id: string; token?: string }
  'Files.generateDownloadToken': { file_id: string }
  'Files.getFile': { file_id: string }
  'Files.getFilePreview': { file_id: string; page?: number }
  'Files.listMessageFiles': { message_id: string }
  'Files.listProjectFiles': { project_id: string; page?: number; per_page?: number; search?: string }
  'Files.removeFileFromMessage': { file_id: string; message_id: string }
  'Files.uploadFile': FormData
  'Files.uploadProjectFile': { project_id: string } & FormData
  'Hub.getHubAssistants': { lang?: string }
  'Hub.getHubModels': { lang?: string }
  'Hub.getHubVersion': void
  'Hub.refreshHubData': { lang?: string }
  'Mcp.cancelExecution': { id: string } & CancelExecutionRequest
  'Mcp.checkConversationApproval': { conversation_id: string; server_id: string; tool_name: string }
  'Mcp.cleanExpiredApprovals': void
  'Mcp.createConversationApproval': { conversation_id: string } & CreateConversationApprovalRequest
  'Mcp.createServer': CreateMCPServerRequest
  'Mcp.deleteConversationApproval': { conversation_id: string; server_id: string; tool_name: string }
  'Mcp.deleteServer': { id: string }
  'Mcp.executeTool': ExecuteToolRequest
  'Mcp.findTool': { server_id?: string }
  'Mcp.getExecutionLog': { id: string }
  'Mcp.getGlobalToolApproval': { server_id: string; tool_name: string }
  'Mcp.getServer': { id: string }
  'Mcp.getServerTools': { id: string }
  'Mcp.getUserAssignedServers': void
  'Mcp.listConversationApprovals': { conversation_id: string; approved?: boolean; include_expired?: boolean; page?: number; per_page?: number; server_id?: string; tool_name?: string }
  'Mcp.listExecutionLogs': { page?: number; per_page?: number; server_id?: string; status?: string; thread_id?: string }
  'Mcp.listServers': { page?: number; per_page?: number; status?: string }
  'Mcp.listThreadExecutionLogs': { thread_id: string }
  'Mcp.listTools': { page?: number; per_page?: number; search?: string; server_id?: string }
  'Mcp.removeToolGlobalApproval': { server_id: string; tool_name: string }
  'Mcp.setToolGlobalApproval': { server_id: string; tool_name: string } & SetToolGlobalApprovalRequest
  'Mcp.startServer': { id: string }
  'Mcp.stopServer': { id: string }
  'Mcp.streamServerLogs': { server_id: string }
  'Mcp.updateServer': { id: string } & UpdateMCPServerRequest
  'Mcp.updateToolApproval': { approval_id: string } & UpdateToolApprovalRequest
  'Models.listEnabledProviderModels': { provider_id: string }
  'Projects.createProject': CreateProjectRequest
  'Projects.deleteProject': { project_id: string }
  'Projects.getProject': { project_id: string }
  'Projects.listProjects': { page?: number; per_page?: number; search?: string }
  'Projects.updateProject': { project_id: string } & UpdateProjectRequest
  'Providers.listEnabledProviders': PaginationQuery
  'Rag.createInstance': { provider_id: string } & CreateRAGInstanceRequest
  'Rag.deleteInstance': { instance_id: string }
  'Rag.deleteInstanceFile': { instance_id: string; file_id: string }
  'Rag.getInstance': { instance_id: string }
  'Rag.listCreatableProviders': void
  'Rag.listInstanceFiles': { instance_id: string; page?: number; per_page?: number; search?: string; status_filter?: RAGProcessingStatus }
  'Rag.listInstances': { include_system?: boolean; page?: number; per_page?: number }
  'Rag.queryInstance': { instance_id: string } & RAGQueryRequest
  'Rag.subscribeInstanceStatus': { instance_id: string; include_files?: boolean }
  'Rag.toggleInstanceActivate': { instance_id: string }
  'Rag.updateInstance': { instance_id: string } & UpdateRAGInstanceRequest
  'Rag.uploadInstanceFile': { instance_id: string } & FormData
  'User.greet': UserHello
  'User.updateAccountPassword': UpdateUserPasswordRequest
  'UserSettings.deleteAllUserSettings': void
  'UserSettings.deleteUserSetting': { key: string }
  'UserSettings.getUserSetting': { key: string }
  'UserSettings.getUserSettings': void
  'UserSettings.setUserSetting': UserSettingRequest
  'Utils.testProxy': TestProxyConnectionRequest
}

// API endpoint responses
export type ApiEndpointResponses = {
  'Admin.addApiProxyServerTrustedHost': ApiProxyServerTrustedHost
  'Admin.addModelToApiProxyServer': ApiProxyServerModel
  'Admin.addModelToProvider': Model
  'Admin.assignUserToGroup': void
  'Admin.cancelDownload': void
  'Admin.createAssistant': Assistant
  'Admin.createGroup': UserGroup
  'Admin.createProvider': Provider
  'Admin.createRAGRepository': RAGRepository
  'Admin.createRagProvider': RAGProvider
  'Admin.createRepository': Repository
  'Admin.createSystemRagInstance': RAGInstance
  'Admin.createUser': User
  'Admin.deleteAssistant': void
  'Admin.deleteDownload': void
  'Admin.deleteGroup': void
  'Admin.deleteModel': void
  'Admin.deleteProvider': void
  'Admin.deleteRAGRepository': void
  'Admin.deleteRagProvider': void
  'Admin.deleteRepository': void
  'Admin.deleteSystemRagInstance': void
  'Admin.deleteUser': void
  'Admin.disableModel': void
  'Admin.downloadFromRepository': DownloadInstance
  'Admin.enableModel': void
  'Admin.getApiProxyServerConfig': ApiProxyServerConfig
  'Admin.getApiProxyServerStatus': ApiProxyServerStatus
  'Admin.getAssistant': Assistant
  'Admin.getAvailableDevices': AvailableDevicesResponse
  'Admin.getDefaultLanguage': DefaultLanguageResponse
  'Admin.getDownload': DownloadInstance
  'Admin.getGroup': UserGroup
  'Admin.getGroupMcpServers': string[]
  'Admin.getGroupMembers': UserListResponse
  'Admin.getGroupProviders': ProviderListResponse
  'Admin.getGroupRagProviders': RAGProviderListResponse
  'Admin.getHardwareInfo': HardwareInfoResponse
  'Admin.getModel': Model
  'Admin.getNgrokSettings': NgrokSettingsResponse
  'Admin.getNgrokStatus': NgrokStatusResponse
  'Admin.getProvider': Provider
  'Admin.getProviderGroups': UserGroup[]
  'Admin.getProxySettings': ProxySettingsResponse
  'Admin.getRAGRepository': RAGRepository
  'Admin.getRagProvider': RAGProvider
  'Admin.getRepository': Repository
  'Admin.getSystemRagInstance': RAGInstance
  'Admin.getUser': User
  'Admin.getUserRegistrationStatus': UserRegistrationStatusResponse
  'Admin.listAllDownloads': DownloadInstanceListResponse
  'Admin.listApiProxyServerModels': ApiProxyServerModel[]
  'Admin.listApiProxyServerTrustedHosts': ApiProxyServerTrustedHost[]
  'Admin.listAssistants': AssistantListResponse
  'Admin.listEngines': EngineInfo[]
  'Admin.listGroups': UserGroupListResponse
  'Admin.listProviderModels': Model[]
  'Admin.listProviders': ProviderListResponse
  'Admin.listRAGRepositories': RAGRepositoryListResponse
  'Admin.listRagProviders': RAGProviderListResponse
  'Admin.listRepositories': RepositoryListResponse
  'Admin.listSystemRagInstances': RAGInstanceListResponse
  'Admin.listUsers': UserListResponse
  'Admin.reloadApiProxyServerModels': void
  'Admin.reloadApiProxyServerTrustedHosts': void
  'Admin.removeApiProxyServerTrustedHost': void
  'Admin.removeModelFromApiProxyServer': void
  'Admin.removeUserFromGroup': void
  'Admin.resetUserPassword': void
  'Admin.startApiProxyServer': void
  'Admin.startModel': void
  'Admin.startNgrokTunnel': NgrokStatusResponse
  'Admin.stopApiProxyServer': void
  'Admin.stopModel': void
  'Admin.stopNgrokTunnel': NgrokStatusResponse
  'Admin.subscribeApiProxyServerLogs': SSEProxyLogsEvent
  'Admin.subscribeDownloadProgress': SSEDownloadProgressEvent
  'Admin.subscribeHardwareUsage': SSEHardwareUsageEvent
  'Admin.testRAGRepositoryConnection': RAGRepositoryConnectionTestResponse
  'Admin.testRagProvider': void
  'Admin.testRepositoryConnection': TestRepositoryConnectionResponse
  'Admin.toggleUserActive': UserActiveStatusResponse
  'Admin.updateApiProxyServerConfig': ApiProxyServerConfig
  'Admin.updateApiProxyServerModel': ApiProxyServerModel
  'Admin.updateApiProxyServerTrustedHost': ApiProxyServerTrustedHost
  'Admin.updateAssistant': Assistant
  'Admin.updateDefaultLanguage': DefaultLanguageResponse
  'Admin.updateGroup': UserGroup
  'Admin.updateModel': Model
  'Admin.updateNgrokSettings': NgrokSettingsResponse
  'Admin.updateProvider': Provider
  'Admin.updateProxySettings': ProxySettingsResponse
  'Admin.updateRAGRepository': RAGRepository
  'Admin.updateRagProvider': RAGProvider
  'Admin.updateRepository': Repository
  'Admin.updateSystemRagInstance': RAGInstance
  'Admin.updateUser': User
  'Admin.updateUserRegistrationStatus': UserRegistrationStatusResponse
  'Admin.uploadAndCommitModel': Model
  'AdminMcp.assignServersToGroup': GroupAssignmentResponse
  'AdminMcp.createSystemServer': MCPServer
  'AdminMcp.getExecutionStatistics': any
  'AdminMcp.getGroupServers': string[]
  'AdminMcp.getServerAccessGroups': string[]
  'AdminMcp.getToolStatistics': any[][]
  'AdminMcp.listAllExecutionLogs': ListExecutionLogsResponse
  'AdminMcp.listAllGroupAssignments': GroupServerAssignmentResponse[]
  'AdminMcp.listSystemServers': ListServersResponse
  'AdminMcp.removeServerFromGroup': void
  'Assistants.createAssistant': Assistant
  'Assistants.deleteAssistant': void
  'Assistants.getAssistant': Assistant
  'Assistants.getDefaultAssistant': Assistant
  'Assistants.listAssistants': AssistantListResponse
  'Assistants.updateAssistant': Assistant
  'Auth.init': InitResponse
  'Auth.login': AuthResponse
  'Auth.logout': void
  'Auth.me': User
  'Auth.register': AuthResponse
  'Auth.setup': AuthResponse
  'Chat.editMessageStream': SSEChatStreamEvent
  'Chat.getConversationMessagesByBranch': Message[]
  'Chat.getMessageBranches': MessageBranch[]
  'Chat.sendMessageStream': SSEChatStreamEvent
  'Config.getDefaultLanguage': DefaultLanguageResponse
  'Config.getUserRegistrationStatus': UserRegistrationStatusResponse
  'Conversation.createConversation': Conversation
  'Conversation.deleteConversation': void
  'Conversation.getConversation': Conversation
  'Conversation.listConversations': ConversationListResponse
  'Conversation.searchConversations': ConversationListResponse
  'Conversation.switchConversationBranch': OperationSuccessResponse
  'Conversation.updateConversation': Conversation
  'Files.deleteFile': FileOperationSuccessResponse
  'Files.downloadFile': Blob
  'Files.downloadFileWithToken': Blob
  'Files.generateDownloadToken': DownloadTokenResponse
  'Files.getFile': File
  'Files.getFilePreview': Blob
  'Files.listMessageFiles': File[]
  'Files.listProjectFiles': FileListResponse
  'Files.removeFileFromMessage': FileOperationSuccessResponse
  'Files.uploadFile': UploadFileResponse
  'Files.uploadProjectFile': UploadFileResponse
  'Hub.getHubAssistants': HubAssistant[]
  'Hub.getHubModels': HubModel[]
  'Hub.getHubVersion': HubVersionResponse
  'Hub.refreshHubData': void
  'Mcp.cancelExecution': any
  'Mcp.checkConversationApproval': ApprovalCheckResponse
  'Mcp.cleanExpiredApprovals': any
  'Mcp.createConversationApproval': ToolApprovalResponse
  'Mcp.createServer': MCPServer
  'Mcp.deleteConversationApproval': SimpleResponse
  'Mcp.deleteServer': void
  'Mcp.executeTool': ToolExecutionResponse
  'Mcp.findTool': MCPToolWithServer | null
  'Mcp.getExecutionLog': MCPExecutionLog
  'Mcp.getGlobalToolApproval': ToolApprovalResponse
  'Mcp.getServer': MCPServer
  'Mcp.getServerTools': MCPTool[]
  'Mcp.getUserAssignedServers': string[]
  'Mcp.listConversationApprovals': ToolApprovalResponse[]
  'Mcp.listExecutionLogs': ListExecutionLogsResponse
  'Mcp.listServers': ListServersResponse
  'Mcp.listThreadExecutionLogs': MCPExecutionLog[]
  'Mcp.listTools': ListToolsResponse
  'Mcp.removeToolGlobalApproval': any
  'Mcp.setToolGlobalApproval': any
  'Mcp.startServer': ServerActionResponse
  'Mcp.stopServer': ServerActionResponse
  'Mcp.streamServerLogs': SSEMCPLogEvent
  'Mcp.updateServer': MCPServer
  'Mcp.updateToolApproval': ToolApprovalResponse
  'Models.listEnabledProviderModels': Model[]
  'Projects.createProject': Project
  'Projects.deleteProject': void
  'Projects.getProject': ProjectDetailResponse
  'Projects.listProjects': ProjectListResponse
  'Projects.updateProject': Project
  'Providers.listEnabledProviders': ProviderListResponse
  'Rag.createInstance': RAGInstance
  'Rag.deleteInstance': void
  'Rag.deleteInstanceFile': FileOperationSuccessResponse
  'Rag.getInstance': RAGInstance
  'Rag.listCreatableProviders': RAGProvider[]
  'Rag.listInstanceFiles': RAGInstanceFilesListResponse
  'Rag.listInstances': RAGInstanceListResponse
  'Rag.queryInstance': RAGQueryResponse
  'Rag.subscribeInstanceStatus': SSERAGStatusEvent
  'Rag.toggleInstanceActivate': RAGInstance
  'Rag.updateInstance': RAGInstance
  'Rag.uploadInstanceFile': UploadFileResponse
  'User.greet': string
  'User.updateAccountPassword': void
  'UserSettings.deleteAllUserSettings': UserSettingsDeletionResponse
  'UserSettings.deleteUserSetting': void
  'UserSettings.getUserSetting': UserSetting
  'UserSettings.getUserSettings': UserSettingsResponse
  'UserSettings.setUserSetting': UserSetting
  'Utils.testProxy': TestProxyConnectionResponse
}

// Type helpers
export type ApiEndpoint = keyof typeof ApiEndpoints
export type ApiEndpointUrl = (typeof ApiEndpoints)[ApiEndpoint]

// Extract endpoint key from URL pattern
export function getEndpointKey(url: string): ApiEndpoint | undefined {
  const entries = Object.entries(ApiEndpoints) as [ApiEndpoint, string][]
  const found = entries.find(([_key, value]) => value === url)
  return found ? found[0] : undefined
}

// Get parameter type for endpoint
export type GetParameterType<K extends ApiEndpoint> = ApiEndpointParameters[K]

// Get response type for endpoint  
export type GetResponseType<K extends ApiEndpoint> = ApiEndpointResponses[K]

// Create reverse mapping from URL to endpoint key
export type UrlToEndpoint<U extends ApiEndpointUrl> = {
  [K in keyof typeof ApiEndpoints]: (typeof ApiEndpoints)[K] extends U
    ? K
    : never
}[keyof typeof ApiEndpoints]

// Helper types to get parameter and response types by URL
export type ParameterByUrl<U extends ApiEndpointUrl> =
  ApiEndpointParameters[UrlToEndpoint<U>]
export type ResponseByUrl<U extends ApiEndpointUrl> =
  ApiEndpointResponses[UrlToEndpoint<U>]

// Type-safe validation - this will cause a TypeScript error if any endpoint is missing
type ValidateParametersComplete = {
  [K in keyof typeof ApiEndpoints]: K extends keyof ApiEndpointParameters
    ? true
    : false
}

type ValidateResponsesComplete = {
  [K in keyof typeof ApiEndpoints]: K extends keyof ApiEndpointResponses
    ? true
    : false
}

// Type-safe validation - these will cause a TypeScript error if any endpoint is missing
// from Parameters or Responses. They are used for compile-time validation only.
export type { ValidateParametersComplete, ValidateResponsesComplete }
